bgcloud2 = {
	{
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "3",
				["y"] = 0,
				["x"] = 1280,
				["name"] = "cloud1A",
				["origVisible"] = true,
				["height"] = 180,
				["file"] = "animation/cloud/cloudA.png",
				["typeName"] = "Image",
				["width"] = 500,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "12",
				["y"] = 0,
				["x"] = 0,
				["name"] = "cloud2A",
				["origVisible"] = true,
				["height"] = 180,
				["file"] = "animation/cloud/cloudA.png",
				["typeName"] = "Image",
				["width"] = 500,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "14",
				["y"] = 100,
				["x"] = 500,
				["name"] = "cloud1B",
				["origVisible"] = true,
				["height"] = 180,
				["file"] = "animation/cloud/cloudB.png",
				["typeName"] = "Image",
				["width"] = 500,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "15",
				["y"] = 100,
				["x"] = 1780,
				["name"] = "cloud2B",
				["origVisible"] = true,
				["height"] = 180,
				["file"] = "animation/cloud/cloudB.png",
				["typeName"] = "Image",
				["width"] = 500,
			},
			["visible"] = 1,
			["time"] = "0",
			["resourceId"] = "2",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Node_small_cloud",
			["xyScale"] = true,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 0,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "9",
				["y"] = 0,
				["x"] = 500,
				["name"] = "Bigcloud1A",
				["origVisible"] = true,
				["height"] = 700,
				["file"] = "animation/cloud/BigcloudA.png",
				["typeName"] = "Image",
				["width"] = 3000,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "11",
				["y"] = 0,
				["x"] = 0,
				["name"] = "Bigcloud1B",
				["origVisible"] = true,
				["height"] = 700,
				["file"] = "animation/cloud/BigcloudB.png",
				["typeName"] = "Image",
				["width"] = 3000,
			},
			["visible"] = 1,
			["time"] = "0",
			["resourceId"] = "8",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Node_big_cloudA",
			["xyScale"] = true,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 0,
		},
		["visible"] = 1,
		["time"] = "0",
		["resourceId"] = "1",
		["y"] = 0,
		["x"] = 0,
		["name"] = "cloud",
		["xyScale"] = false,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["width"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 100000,
		["animType"] = 1,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "3",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -1280,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 50000,
		["animType"] = 1,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "11",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -3840,
		["easeType"] = "Nil",
		["id"] = "8",
		["duration"] = 200000,
		["animType"] = 1,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0.800,
		["delay"] = 0,
		["endValue"] = 0.800,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "12",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}