coinflash3 = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "8",
			["y"] = 0,
			["x"] = 0,
			["name"] = "item_icon3",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "shop/item_icon3.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "3",
			["y"] = 34,
			["x"] = 93,
			["name"] = "star1",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "animation/cointime/star.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "5",
			["y"] = 10,
			["x"] = 38,
			["name"] = "star2",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "animation/cointime/star.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "6",
			["y"] = 49,
			["x"] = 20,
			["name"] = "star3",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "animation/cointime/star.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["resourceId"] = "1",
		["y"] = 0,
		["x"] = 0,
		["name"] = "cointime",
		["filter"] = 1,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["width"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "8",
		["duration"] = 1000,
		["animType"] = 2,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["startValueX"] = 0.200,
		["endValueX"] = 0.800,
		["id"] = "3",
		["duration"] = 1000,
		["animType"] = 2,
		["endValueY"] = 0.800,
		["startValueY"] = 0.200,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "3",
		["duration"] = 1000,
		["animType"] = 1,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = 90,
	},
	{
		["startValueX"] = 0.200,
		["endValueX"] = 0.800,
		["id"] = "5",
		["duration"] = 1000,
		["animType"] = 2,
		["endValueY"] = 0.800,
		["startValueY"] = 0.200,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 1000,
		["animType"] = 1,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = 90,
	},
	{
		["startValueX"] = 0.200,
		["endValueX"] = 0.800,
		["id"] = "6",
		["duration"] = 1000,
		["animType"] = 2,
		["endValueY"] = 0.800,
		["startValueY"] = 0.200,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 1000,
		["animType"] = 1,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = 90,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}