flower = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["width"] = 0,
			["resourceId"] = "17",
			["y"] = 15,
			["x"] = 70,
			["name"] = "ink0001",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "ink0001.png",
			["typeName"] = "Image",
			["packFile"] = "pin_map/flower.lua",
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "15",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flower1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flower1.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "16",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flower2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flower2.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "14",
			["y"] = -10,
			["x"] = 110,
			["name"] = "Node_flower4",
			["filter"] = 1,
			["height"] = 83,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 91,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "12",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flower1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flower1.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "13",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flower2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flower2.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "11",
			["y"] = 70,
			["x"] = 255,
			["name"] = "Node_flower3",
			["filter"] = 1,
			["height"] = 83,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 91,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "3",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flowertext1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flowertext1.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "4",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flowertext2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flowertext2.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "2",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Node_flowertext",
			["filter"] = 1,
			["height"] = 164,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 277,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "7",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flower1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flower1.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "8",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flower2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flower2.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "5",
			["y"] = 55,
			["x"] = -60,
			["name"] = "Node_flower1",
			["filter"] = 1,
			["height"] = 83,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 91,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "9",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flower1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flower1.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["width"] = 0,
				["resourceId"] = "10",
				["y"] = 0,
				["x"] = 0,
				["name"] = "flower2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "flower2.png",
				["typeName"] = "Image",
				["packFile"] = "pin_map/flower.lua",
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "6",
			["y"] = 80,
			["x"] = 300,
			["name"] = "Node_flower2",
			["filter"] = 1,
			["height"] = 83,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 91,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["width"] = 0,
			["resourceId"] = "19",
			["y"] = -50,
			["x"] = -70,
			["name"] = "flower1",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "flower.png",
			["typeName"] = "Image",
			["packFile"] = "pin_map/flower.lua",
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["width"] = 0,
			["resourceId"] = "20",
			["y"] = -25,
			["x"] = -40,
			["name"] = "flower2",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "flower.png",
			["typeName"] = "Image",
			["packFile"] = "pin_map/flower.lua",
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["width"] = 0,
			["resourceId"] = "21",
			["y"] = -80,
			["x"] = -70,
			["name"] = "flower3",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "flower.png",
			["typeName"] = "Image",
			["packFile"] = "pin_map/flower.lua",
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["width"] = 0,
			["resourceId"] = "22",
			["y"] = 60,
			["x"] = -80,
			["name"] = "flower4",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "flower.png",
			["typeName"] = "Image",
			["packFile"] = "pin_map/flower.lua",
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["width"] = 0,
			["resourceId"] = "23",
			["y"] = 5,
			["x"] = -75,
			["name"] = "flower5",
			["filter"] = 1,
			["height"] = 0,
			["file"] = "flower.png",
			["typeName"] = "Image",
			["packFile"] = "pin_map/flower.lua",
		},
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["width"] = 0,
		["y"] = 100,
		["x"] = 300,
		["name"] = "Node_Relati",
		["filter"] = 1,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["resourceId"] = "1",
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "17",
		["duration"] = 2000,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 2000,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "16",
		["duration"] = 2000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "16",
		["duration"] = 200,
		["delay"] = 200,
		["animType"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 200,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 400,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "12",
		["duration"] = 2000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 200,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "13",
		["duration"] = 1800,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 200,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 100,
		["delay"] = 200,
		["animType"] = 0,
	},
	{
		["startValueX"] = 0.900,
		["endValueX"] = 0.900,
		["id"] = "11",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 0.900,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 200,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "11",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 200,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "11",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 300,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "3",
		["duration"] = 2000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "3",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "4",
		["duration"] = 2000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "4",
		["duration"] = 200,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["startValueX"] = 1.500,
		["endValueX"] = 1,
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1.500,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "7",
		["duration"] = 2000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.830,
		["id"] = "7",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.830,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "7",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 300,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.900,
		["id"] = "7",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 500,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "8",
		["duration"] = 2000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.830,
		["id"] = "8",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.830,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "8",
		["duration"] = 200,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["startValueX"] = 1.200,
		["endValueX"] = 1.200,
		["id"] = "5",
		["duration"] = 1000,
		["animType"] = 2,
		["endValueY"] = 1.200,
		["startValueY"] = 1.200,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "9",
		["duration"] = 2000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "9",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "9",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 300,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "10",
		["duration"] = 2000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "10",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 200,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["startValueX"] = 0.500,
		["endValueX"] = 0.500,
		["id"] = "6",
		["duration"] = 1000,
		["animType"] = 2,
		["endValueY"] = 0.500,
		["startValueY"] = 0.500,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 170,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 800,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 75,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 180,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 700,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 30,
		["delay"] = 800,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 1500,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = 360,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 300,
		["delay"] = 0,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 20,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 300,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 10,
		["delay"] = 100,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 190,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 600,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 90,
		["delay"] = 400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 180,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 600,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 20,
		["delay"] = 1000,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 300,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 200,
		["delay"] = 1400,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 1600,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = -360,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 120,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 400,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 65,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 100,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 300,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 700,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 80,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 500,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 30,
		["delay"] = 1000,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 100,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 400,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 1500,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 400,
		["delay"] = 300,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 300,
		["delay"] = 1600,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 1600,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 300,
		["endValue"] = 180,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 60,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 500,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 200,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 700,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 80,
		["delay"] = 700,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 150,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 600,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 1400,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 200,
		["delay"] = 500,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 300,
		["delay"] = 1700,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 1500,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 500,
		["endValue"] = 360,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 80,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 900,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 180,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 600,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 100,
		["delay"] = 1100,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 100,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 300,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 10,
		["delay"] = 1700,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 200,
		["delay"] = 900,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 1100,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 900,
		["endValue"] = 360,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "1",
		["duration"] = 200,
		["delay"] = 1800,
		["animType"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}