grade = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "18",
			["y"] = 0,
			["x"] = 0,
			["name"] = "light",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/grade/light.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "19",
			["y"] = 250,
			["x"] = 40,
			["name"] = "sequence",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = {
				"animation/grade/grade1.png",
				"animation/grade/grade2.png",
				"animation/grade/grade3.png",
				"animation/grade/grade4.png",
				"animation/grade/grade5.png",
				"animation/grade/grade6.png",
				"animation/grade/grade7.png",
				"animation/grade/grade8.png",
				"animation/grade/grade9.png",
				"animation/grade/grade10.png",
				"animation/grade/grade11.png",
				"animation/grade/grade12.png",
				"animation/grade/grade13.png",
				"animation/grade/grade14.png",
				"animation/grade/grade15.png",
				"animation/grade/grade16.png",
				"animation/grade/grade17.png",
				"animation/grade/grade18.png",
				"animation/grade/grade19.png",
				"animation/grade/grade20.png",
				"animation/grade/grade21.png",
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "20",
			["y"] = 250,
			["x"] = 40,
			["name"] = "grade21",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/grade/grade21.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		["visible"] = 1,
		["time"] = "0",
		["resourceId"] = "14",
		["y"] = 0,
		["x"] = 0,
		["name"] = "grade",
		["xyScale"] = false,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["width"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 2500,
		["animType"] = 0,
		["centerType"] = 1,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 1500,
		["endValue"] = 100,
	},
	{
		["num"] = 21,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 2500,
		["delay"] = 0,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 1500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 2500,
		["startValueX"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 1280,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 720,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}