guangDong = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = false,
			["resourceId"] = "14",
			["y"] = 360,
			["x"] = 40,
			["name"] = "stage",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/guangDong/stage.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = false,
			["resourceId"] = "2",
			["y"] = 173,
			["x"] = 52,
			["name"] = "house",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/guangDong/house.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = false,
			["resourceId"] = "41",
			["y"] = 335,
			["x"] = 100,
			["name"] = "box",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/guangDong/box.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "45",
				["y"] = 380,
				["x"] = -15,
				["name"] = "shadow",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = "animation/guangDong/shadow.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "26",
				["y"] = 240,
				["x"] = -10,
				["name"] = "skirt",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = "animation/guangDong/skirt.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				{
					{
						{
							{
								["visible"] = 1,
								["time"] = "0",
								["xyScale"] = true,
								["resourceId"] = "38",
								["y"] = 0,
								["x"] = 0,
								["name"] = "bird",
								["origVisible"] = true,
								["height"] = 0,
								["file"] = "animation/guangDong/bird.png",
								["typeName"] = "Image",
								["width"] = 0,
							},
							{
								["visible"] = 1,
								["time"] = "0",
								["xyScale"] = true,
								["resourceId"] = "39",
								["y"] = 13,
								["x"] = -6,
								["name"] = "birdWing",
								["origVisible"] = true,
								["height"] = 0,
								["file"] = "animation/guangDong/birdWing.png",
								["typeName"] = "Image",
								["width"] = 0,
							},
							["visible"] = 1,
							["time"] = "0",
							["resourceId"] = "37",
							["y"] = -38,
							["x"] = -11,
							["name"] = "Node_bird",
							["xyScale"] = true,
							["height"] = 0,
							["origVisible"] = true,
							["typeName"] = "",
							["width"] = 0,
						},
						["visible"] = 1,
						["time"] = "0",
						["xyScale"] = true,
						["resourceId"] = "35",
						["y"] = 0,
						["x"] = 0,
						["name"] = "leftArm",
						["origVisible"] = true,
						["height"] = 0,
						["file"] = "animation/guangDong/leftArm.png",
						["typeName"] = "Image",
						["width"] = 0,
					},
					["visible"] = 1,
					["time"] = "0",
					["resourceId"] = "34",
					["y"] = 90,
					["x"] = -80,
					["name"] = "Node_leftArm",
					["xyScale"] = true,
					["height"] = 0,
					["origVisible"] = true,
					["typeName"] = "",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "24",
					["y"] = 117,
					["x"] = 20,
					["name"] = "body",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guangDong/body.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					{
						{
							["visible"] = 1,
							["time"] = "0",
							["xyScale"] = true,
							["resourceId"] = "32",
							["y"] = 20,
							["x"] = 8,
							["name"] = "handkerchief",
							["origVisible"] = true,
							["height"] = 0,
							["file"] = "animation/guangDong/handkerchief.png",
							["typeName"] = "Image",
							["width"] = 0,
						},
						{
							["visible"] = 1,
							["time"] = "0",
							["xyScale"] = true,
							["resourceId"] = "33",
							["y"] = 0,
							["x"] = 0,
							["name"] = "rightHand",
							["origVisible"] = true,
							["height"] = 0,
							["file"] = "animation/guangDong/rightHand.png",
							["typeName"] = "Image",
							["width"] = 0,
						},
						["visible"] = 1,
						["time"] = "0",
						["resourceId"] = "31",
						["y"] = 85,
						["x"] = 60,
						["name"] = "Node_rightHand",
						["xyScale"] = true,
						["height"] = 0,
						["origVisible"] = true,
						["typeName"] = "",
						["width"] = 0,
					},
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "27",
					["y"] = 160,
					["x"] = 90,
					["name"] = "rightArm",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guangDong/rightArm.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "40",
					["y"] = 0,
					["x"] = 0,
					["name"] = "head",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guangDong/head1.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "42",
					["y"] = 0,
					["x"] = 0,
					["name"] = "Image_head",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = {
						"animation/guangDong/head1.png",
						"animation/guangDong/head2.png",
						"animation/guangDong/head3.png",
						"animation/guangDong/head2.png",
						"animation/guangDong/head1.png",
					},
					["typeName"] = "AnimFrame",
					["width"] = 0,
				},
				["visible"] = 1,
				["time"] = "0",
				["resourceId"] = "43",
				["y"] = 0,
				["x"] = 0,
				["name"] = "Node_body",
				["xyScale"] = false,
				["height"] = 0,
				["origVisible"] = true,
				["typeName"] = "",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["resourceId"] = "22",
			["y"] = -5,
			["x"] = 410,
			["name"] = "Node",
			["xyScale"] = false,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 0,
		},
		["visible"] = 1,
		["time"] = "0",
		["resourceId"] = "44",
		["y"] = 200,
		["x"] = 400,
		["name"] = "Node_292",
		["xyScale"] = false,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["width"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 3200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 3500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 3500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "32",
		["duration"] = 3500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "38",
		["duration"] = 3500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "39",
		["duration"] = 3500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "40",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 80,
		["startValue"] = 0,
		["centerY"] = 130,
		["delay"] = 300,
		["endValue"] = -7,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "40",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 80,
		["startValue"] = 0,
		["centerY"] = 130,
		["delay"] = 500,
		["endValue"] = 7,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "40",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 80,
		["startValue"] = 0,
		["centerY"] = 130,
		["delay"] = 600,
		["endValue"] = -4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "40",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 80,
		["startValue"] = 0,
		["centerY"] = 130,
		["delay"] = 700,
		["endValue"] = 4,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "40",
		["duration"] = 800,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 0.070,
		["startValueX"] = 0.210,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1,
		["centerY"] = 206,
		["delay"] = 0,
		["centerX"] = 123,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0.400,
		["delay"] = 0,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -60,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 25,
		["delay"] = 300,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "41",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 0.070,
		["startValueX"] = 0.150,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1,
		["centerY"] = 83,
		["delay"] = 200,
		["centerX"] = 73,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.150,
		["easeType"] = "Nil",
		["id"] = "41",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.150,
		["centerY"] = 83,
		["delay"] = 300,
		["centerX"] = 73,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.870,
		["easeType"] = "Nil",
		["id"] = "41",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.870,
		["centerY"] = 83,
		["delay"] = 400,
		["centerX"] = 73,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "41",
		["duration"] = 2500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 500,
		["startValueX"] = 0,
	},
	{
		["num"] = 5,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "42",
		["duration"] = 500,
		["delay"] = 800,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "40",
		["duration"] = 1100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 20,
		["delay"] = 500,
		["endValue"] = 12.500,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 20,
		["delay"] = 600,
		["endValue"] = -2.500,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 20,
		["delay"] = 1000,
		["endValue"] = -2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "32",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 300,
		["endValue"] = -8,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.150,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.150,
		["centerY"] = 206,
		["delay"] = 100,
		["centerX"] = 123,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.870,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.870,
		["centerY"] = 206,
		["delay"] = 200,
		["centerX"] = 123,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 2700,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "32",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 500,
		["endValue"] = -11,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "32",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 600,
		["endValue"] = 17,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "34",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 117,
		["startValue"] = 0,
		["centerY"] = 83,
		["delay"] = 600,
		["endValue"] = -2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "34",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 117,
		["startValue"] = 0,
		["centerY"] = 83,
		["delay"] = 700,
		["endValue"] = 2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "34",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 117,
		["startValue"] = 0,
		["centerY"] = 83,
		["delay"] = 1000,
		["endValue"] = 4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "34",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 117,
		["startValue"] = 0,
		["centerY"] = 83,
		["delay"] = 1100,
		["endValue"] = -4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "34",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 117,
		["startValue"] = 0,
		["centerY"] = 83,
		["delay"] = 1300,
		["endValue"] = 4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "34",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 117,
		["startValue"] = 0,
		["centerY"] = 83,
		["delay"] = 1400,
		["endValue"] = -4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "37",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 29,
		["startValue"] = 0,
		["centerY"] = 42,
		["delay"] = 300,
		["endValue"] = 17,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "37",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 29,
		["startValue"] = 0,
		["centerY"] = 42,
		["delay"] = 500,
		["endValue"] = -17,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "37",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 29,
		["startValue"] = 0,
		["centerY"] = 42,
		["delay"] = 600,
		["endValue"] = 15,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "37",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 29,
		["startValue"] = 0,
		["centerY"] = 42,
		["delay"] = 700,
		["endValue"] = -15,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "39",
		["duration"] = 100,
		["animType"] = 2,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 29,
		["startValue"] = 0,
		["centerY"] = 11,
		["delay"] = 1500,
		["endValue"] = -20,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -100,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 100,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -2,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 200,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -134,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3200,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -90,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3300,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 500,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3200,
		["endValue"] = 0.400,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "43",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 50,
		["startValue"] = 0,
		["centerY"] = 250,
		["delay"] = 300,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "43",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 50,
		["startValue"] = 0,
		["centerY"] = 250,
		["delay"] = 500,
		["endValue"] = 7,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.060,
		["easeType"] = "Nil",
		["id"] = "41",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.060,
		["centerY"] = 83,
		["delay"] = 3000,
		["centerX"] = 73,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.180,
		["easeType"] = "Nil",
		["id"] = "41",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.120,
		["centerY"] = 83,
		["delay"] = 3100,
		["centerX"] = 73,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.050,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.050,
		["centerY"] = 206,
		["delay"] = 3000,
		["centerX"] = 123,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.200,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.070,
		["centerY"] = 206,
		["delay"] = 3100,
		["centerX"] = 123,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "43",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 50,
		["startValue"] = 0,
		["centerY"] = 250,
		["delay"] = 600,
		["endValue"] = -2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 20,
		["delay"] = 1100,
		["endValue"] = 2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "43",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 50,
		["startValue"] = 0,
		["centerY"] = 250,
		["delay"] = 3100,
		["endValue"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "33",
		["duration"] = 3500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "33",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 300,
		["endValue"] = -3,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "33",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 500,
		["endValue"] = 3,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "32",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 700,
		["endValue"] = 2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "32",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 1000,
		["endValue"] = 5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "32",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 1100,
		["endValue"] = -5,
	},
	{
		["num"] = 5,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "42",
		["duration"] = 400,
		["delay"] = 2400,
		["animType"] = 0,
	},
	{
		["num"] = 3,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "42",
		["duration"] = 200,
		["delay"] = 3300,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "40",
		["duration"] = 500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 2800,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "45",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 300,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "45",
		["duration"] = 2700,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 500,
		["startValueX"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}