guobiao = {
	{
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["resourceId"] = "2",
		["y"] = 0,
		["x"] = 0,
		["name"] = "hall",
		["origVisible"] = true,
		["height"] = 0,
		["file"] = "animation/guobiao/hall.png",
		["typeName"] = "Image",
		["width"] = 0,
	},
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "46",
			["y"] = 275,
			["x"] = -120,
			["name"] = "wutai",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/guobiao/wutai.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "47",
			["y"] = 120,
			["x"] = -130,
			["name"] = "pingfeng2",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/guobiao/pingfeng2.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "48",
			["y"] = 285,
			["x"] = -30,
			["name"] = "majiangxiang",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/guobiao/majiangxiang.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			{
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "22",
					["y"] = 0,
					["x"] = 130,
					["name"] = "bianzi",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guobiao/bianzi.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "15",
					["y"] = 70,
					["x"] = -17,
					["name"] = "zuobinfa",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guobiao/zuobinfa.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "43",
					["y"] = 0,
					["x"] = 0,
					["name"] = "Image_tou_seq2",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = {
						"animation/guobiao/toukai.png",
						"animation/guobiao/touban.png",
						"animation/guobiao/toubi.png",
					},
					["typeName"] = "AnimFrame",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "42",
					["y"] = 0,
					["x"] = 0,
					["name"] = "Image_tou_seq1",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = {
						"animation/guobiao/toukai.png",
						"animation/guobiao/touban.png",
						"animation/guobiao/toubi.png",
					},
					["typeName"] = "AnimFrame",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "13",
					["y"] = 0,
					["x"] = 0,
					["name"] = "toubi",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guobiao/toubi.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "44",
					["y"] = 0,
					["x"] = 0,
					["name"] = "touban",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guobiao/touban.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "45",
					["y"] = 0,
					["x"] = 0,
					["name"] = "toukai",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guobiao/toukai.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "14",
					["y"] = 90,
					["x"] = 70,
					["name"] = "youbinfa",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guobiao/youbinfa.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				["visible"] = 1,
				["time"] = "0",
				["width"] = 0,
				["y"] = -100,
				["x"] = -100,
				["name"] = "head",
				["resourceId"] = "12",
				["height"] = 0,
				["origVisible"] = true,
				["typeName"] = "",
				["xyScale"] = true,
			},
			{
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "27",
					["y"] = 50,
					["x"] = 80,
					["name"] = "hougebo",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guobiao/hougebo.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "24",
					["y"] = 0,
					["x"] = 0,
					["name"] = "shenti",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/guobiao/shenti.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					{
						["visible"] = 1,
						["time"] = "0",
						["xyScale"] = true,
						["resourceId"] = "31",
						["y"] = 25,
						["x"] = 10,
						["name"] = "nashangebo",
						["origVisible"] = true,
						["height"] = 0,
						["file"] = "animation/guobiao/nashangebo.png",
						["typeName"] = "Image",
						["width"] = 0,
					},
					{
						{
							["visible"] = 1,
							["time"] = "0",
							["xyScale"] = true,
							["resourceId"] = "36",
							["y"] = 10,
							["x"] = -25,
							["name"] = "shanzi",
							["origVisible"] = true,
							["height"] = 0,
							["file"] = "animation/guobiao/shanzi.png",
							["typeName"] = "Image",
							["width"] = 0,
						},
						{
							["visible"] = 1,
							["time"] = "0",
							["xyScale"] = true,
							["resourceId"] = "37",
							["y"] = 90,
							["x"] = -30,
							["name"] = "nashanshou",
							["origVisible"] = true,
							["height"] = 0,
							["file"] = "animation/guobiao/nashanshou.png",
							["typeName"] = "Image",
							["width"] = 0,
						},
						{
							["visible"] = 1,
							["time"] = "0",
							["xyScale"] = true,
							["resourceId"] = "38",
							["y"] = 125,
							["x"] = -25,
							["name"] = "shansheng",
							["origVisible"] = true,
							["height"] = 0,
							["file"] = "animation/guobiao/shansheng.png",
							["typeName"] = "Image",
							["width"] = 0,
						},
						["visible"] = 1,
						["time"] = "0",
						["resourceId"] = "35",
						["y"] = 0,
						["x"] = 0,
						["name"] = "Node_sanzi",
						["xyScale"] = true,
						["height"] = 0,
						["origVisible"] = true,
						["typeName"] = "",
						["width"] = 0,
					},
					["visible"] = 1,
					["time"] = "0",
					["resourceId"] = "30",
					["y"] = 0,
					["x"] = 0,
					["name"] = "Node_nashanshou",
					["xyScale"] = true,
					["height"] = 0,
					["origVisible"] = true,
					["typeName"] = "",
					["width"] = 0,
				},
				["visible"] = 1,
				["time"] = "0",
				["resourceId"] = "23",
				["y"] = 5,
				["x"] = -85,
				["name"] = "Node_shenti",
				["xyScale"] = true,
				["height"] = 0,
				["origVisible"] = true,
				["typeName"] = "",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "50",
				["y"] = 125,
				["x"] = -95,
				["name"] = "Image_bufferfly_big_seq_1",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = {
					"animation/bufferfly/butterfly0001.png",
					"animation/bufferfly/butterfly0002.png",
					"animation/bufferfly/butterfly0003.png",
					"animation/bufferfly/butterfly0004.png",
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "54",
				["y"] = 70,
				["x"] = -200,
				["name"] = "Image_tail_l",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = {
					"animation/tail_l/tail0006.png",
					"animation/tail_l/tail0010.png",
					"animation/tail_l/tail0014.png",
					"animation/tail_l/tail0018.png",
					"animation/tail_l/tail0022.png",
					"animation/tail_l/tail0026.png",
					"animation/tail_l/tail0030.png",
					"animation/tail_l/tail0034.png",
					"animation/tail_l/tail0038.png",
					"animation/tail_l/tail0042.png",
					"animation/tail_l/tail0046.png",
					"animation/tail_l/tail0050.png",
					"animation/tail_l/tail0054.png",
					"animation/tail_l/tail0058.png",
					"animation/tail_l/tail0062.png",
					"animation/tail_l/tail0066.png",
					"animation/tail_l/tail0070.png",
					"animation/tail_l/tail0074.png",
					"animation/tail_l/tail0078.png",
					"animation/tail_l/tail0082.png",
					"animation/tail_l/tail0086.png",
					"animation/tail_l/tail0090.png",
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["resourceId"] = "3",
			["y"] = 0,
			["x"] = 400,
			["name"] = "Node_body",
			["xyScale"] = true,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "52",
			["y"] = 180,
			["x"] = 200,
			["name"] = "Image_bufferfly_small_seq",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = {
				"animation/bufferfly/butterfly_small0001.png",
				"animation/bufferfly/butterfly_small0002.png",
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "53",
			["y"] = 40,
			["x"] = 200,
			["name"] = "Image_bufferfly_small_seq2",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = {
				"animation/bufferfly/butterfly_small0001.png",
				"animation/bufferfly/butterfly_small0002.png",
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "55",
			["y"] = 125,
			["x"] = 190,
			["name"] = "Image_mail_1_seq",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = {
				"animation/tail_s/tail0016.png",
				"animation/tail_s/tail0020.png",
				"animation/tail_s/tail0024.png",
				"animation/tail_s/tail0028.png",
				"animation/tail_s/tail0032.png",
				"animation/tail_s/tail0036.png",
				"animation/tail_s/tail0040.png",
				"animation/tail_s/tail0044.png",
				"animation/tail_s/tail0048.png",
				"animation/tail_s/tail0052.png",
				"animation/tail_s/tail0056.png",
				"animation/tail_s/tail0060.png",
				"animation/tail_s/tail0064.png",
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "56",
			["y"] = 0,
			["x"] = 180,
			["name"] = "Image_mail_2_seq",
			["origVisible"] = true,
			["height"] = 90,
			["file"] = {
				"animation/tail_s/tail0016.png",
				"animation/tail_s/tail0020.png",
				"animation/tail_s/tail0024.png",
				"animation/tail_s/tail0028.png",
				"animation/tail_s/tail0032.png",
				"animation/tail_s/tail0036.png",
				"animation/tail_s/tail0040.png",
				"animation/tail_s/tail0044.png",
				"animation/tail_s/tail0048.png",
				"animation/tail_s/tail0052.png",
				"animation/tail_s/tail0056.png",
				"animation/tail_s/tail0060.png",
				"animation/tail_s/tail0064.png",
			},
			["typeName"] = "AnimFrame",
			["width"] = 36,
		},
		["visible"] = 1,
		["time"] = "0",
		["width"] = 0,
		["y"] = 200,
		["x"] = 700,
		["name"] = "Node_relat",
		["resourceId"] = "1",
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["xyScale"] = false,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -210,
		["easeType"] = "Nil",
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 0,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 37,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 400,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 32,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 400,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "3",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 110,
		["startValue"] = 0,
		["centerY"] = 420,
		["delay"] = 100,
		["endValue"] = -2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 110,
		["startValue"] = 0,
		["centerY"] = 420,
		["delay"] = 300,
		["endValue"] = 2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "12",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 80,
		["startValue"] = 0,
		["centerY"] = 150,
		["delay"] = 100,
		["endValue"] = -8,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "12",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 80,
		["startValue"] = 0,
		["centerY"] = 150,
		["delay"] = 300,
		["endValue"] = 8,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 110,
		["startValue"] = 0,
		["centerY"] = 420,
		["delay"] = 400,
		["endValue"] = -1,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 100,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 1,
		["centerY"] = 0,
		["delay"] = 300,
		["endValue"] = 5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 0,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 400,
		["endValue"] = -2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "31",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "30",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 35,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 100,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "30",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 35,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 300,
		["endValue"] = 5,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "38",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "37",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "36",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "38",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 5,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 100,
		["endValue"] = 60,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "38",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 5,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 300,
		["endValue"] = -65,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "38",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 5,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 400,
		["endValue"] = 20,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "35",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 10,
		["startValue"] = 0,
		["centerY"] = 120,
		["delay"] = 1000,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "35",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 10,
		["startValue"] = 0,
		["centerY"] = 120,
		["delay"] = 1100,
		["endValue"] = 10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "35",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 10,
		["startValue"] = 0,
		["centerY"] = 120,
		["delay"] = 1200,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "35",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 10,
		["startValue"] = 0,
		["centerY"] = 120,
		["delay"] = 1300,
		["endValue"] = 10,
	},
	{
		["num"] = 3,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "42",
		["duration"] = 250,
		["delay"] = 1500,
		["animType"] = 0,
	},
	{
		["num"] = 3,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "43",
		["duration"] = 250,
		["delay"] = 1750,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "44",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 1050,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "45",
		["duration"] = 400,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 1100,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 1050,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 0,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "45",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 2000,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "46",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "47",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 0.060,
		["startValueX"] = 0.060,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1,
		["centerY"] = 215,
		["delay"] = 0,
		["centerX"] = 130,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.300,
		["easeType"] = "Nil",
		["id"] = "47",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.300,
		["centerY"] = 215,
		["delay"] = 100,
		["centerX"] = 130,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.760,
		["easeType"] = "Nil",
		["id"] = "47",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.760,
		["centerY"] = 215,
		["delay"] = 300,
		["centerX"] = 130,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "47",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 500,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.200,
		["easeType"] = "Nil",
		["id"] = "48",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 0.100,
		["startValueX"] = 0.100,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 40,
		["delay"] = 100,
		["centerX"] = 70,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.830,
		["easeType"] = "Nil",
		["id"] = "48",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.830,
		["centerY"] = 40,
		["delay"] = 300,
		["centerX"] = 70,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "48",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 500,
		["startValueX"] = 0,
	},
	{
		["num"] = 4,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 100,
		["delay"] = 300,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -100,
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 1000,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = -50,
		["startValueY"] = 0,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 1000,
		["animType"] = 0,
		["centerType"] = 1,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 90,
		["centerY"] = 0,
		["delay"] = 1300,
		["endValue"] = 90,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -100,
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 2000,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = -60,
		["startValueY"] = 0,
		["delay"] = 1300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 500,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 2800,
		["endValue"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 50,
		["delay"] = 0,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 45,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = 45,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0.200,
		["delay"] = 0,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -50,
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 1900,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = -100,
		["startValueY"] = 0,
		["delay"] = 100,
		["startValueX"] = 1,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 300,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 1700,
		["endValue"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "53",
		["duration"] = 50,
		["delay"] = 300,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "53",
		["duration"] = 200,
		["animType"] = 2,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 300,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -50,
		["easeType"] = "Nil",
		["id"] = "53",
		["duration"] = 2300,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = -150,
		["startValueY"] = 0,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "53",
		["duration"] = 500,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 1700,
		["endValue"] = 0,
	},
	{
		["num"] = 22,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "54",
		["duration"] = 2900,
		["delay"] = 600,
		["animType"] = 0,
	},
	{
		["num"] = 13,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "55",
		["duration"] = 2000,
		["delay"] = 700,
		["animType"] = 0,
	},
	{
		["num"] = 13,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "56",
		["duration"] = 2000,
		["delay"] = 1100,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "56",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = -45,
		["centerY"] = 0,
		["delay"] = 1100,
		["endValue"] = -45,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}