guobiao_bufferly = {
	{
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "50",
				["y"] = 125,
				["x"] = -95,
				["name"] = "Image_bufferfly_big_seq_1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = {
					{
						["packFile"] = "pin_map/guobiaoentergril_pin.lua",
						["path"] = "butterfly0001.png",
					},
					{
						["packFile"] = "pin_map/guobiaoentergril_pin.lua",
						["path"] = "butterfly0002.png",
					},
					{
						["packFile"] = "pin_map/guobiaoentergril_pin.lua",
						["path"] = "animation/bufferfly/butterfly0003.png",
					},
					{
						["packFile"] = "pin_map/guobiaoentergril_pin.lua",
						["path"] = "animation/bufferfly/butterfly0004.png",
					},
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "54",
				["y"] = 70,
				["x"] = -200,
				["name"] = "Image_tail_l",
				["filter"] = 1,
				["height"] = 0,
				["file"] = {
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0006.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0010.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0014.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0018.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0022.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0026.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0030.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0034.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0038.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0042.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0046.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0050.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0054.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0058.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0062.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0066.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0070.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0074.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0078.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0082.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0086.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0090.png",
					},
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "3",
			["y"] = 0,
			["x"] = 190,
			["name"] = "Node_body",
			["filter"] = 1,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "52",
			["y"] = 180,
			["x"] = 200,
			["name"] = "Image_bufferfly_small_seq",
			["filter"] = 1,
			["height"] = 0,
			["file"] = {
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "butterfly_small0001.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "butterfly_small0002.png",
				},
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "53",
			["y"] = 40,
			["x"] = 200,
			["name"] = "Image_bufferfly_small_seq2",
			["filter"] = 1,
			["height"] = 0,
			["file"] = {
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "butterfly_small0001.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "butterfly_small0002.png",
				},
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "55",
			["y"] = 125,
			["x"] = 190,
			["name"] = "Image_mail_1_seq",
			["filter"] = 1,
			["height"] = 0,
			["file"] = {
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0016.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0020.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0024.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0028.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0032.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0036.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0040.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0044.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0048.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0052.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0056.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0060.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0064.png",
				},
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "56",
			["y"] = 0,
			["x"] = 180,
			["name"] = "Image_mail_2_seq",
			["filter"] = 1,
			["height"] = 90,
			["file"] = {
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0016.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0020.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0024.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0028.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0032.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0036.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0040.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0044.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0048.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0052.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0056.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0060.png",
				},
				{
					["packFile"] = "pin_map/guobiaoentergril_pin.lua",
					["path"] = "tail0064.png",
				},
			},
			["typeName"] = "AnimFrame",
			["width"] = 36,
		},
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["width"] = 0,
		["y"] = 0,
		["x"] = 0,
		["name"] = "Node_relat",
		["filter"] = 1,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["resourceId"] = "1",
	},
	{
		["num"] = 4,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 100,
		["delay"] = 300,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -100,
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 1000,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = -50,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 90,
		["centerY"] = 0,
		["delay"] = 1300,
		["endValue"] = 90,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -100,
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 2000,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = -60,
		["delay"] = 1300,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "50",
		["duration"] = 500,
		["delay"] = 2800,
		["animType"] = 0,
	},
	{
		["num"] = 22,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "54",
		["duration"] = 2900,
		["delay"] = 600,
		["animType"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 50,
		["delay"] = 0,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 45,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = 45,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0.200,
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 100,
		["delay"] = 0,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -50,
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 1900,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = -100,
		["delay"] = 100,
		["startValueX"] = 1,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "52",
		["duration"] = 300,
		["delay"] = 1700,
		["animType"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "53",
		["duration"] = 50,
		["delay"] = 300,
		["animType"] = 2,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "53",
		["duration"] = 200,
		["delay"] = 300,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -50,
		["easeType"] = "Nil",
		["id"] = "53",
		["duration"] = 1900,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = -150,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "53",
		["duration"] = 500,
		["delay"] = 1700,
		["animType"] = 0,
	},
	{
		["num"] = 13,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "55",
		["duration"] = 2000,
		["delay"] = 700,
		["animType"] = 0,
	},
	{
		["num"] = 13,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "56",
		["duration"] = 2000,
		["delay"] = 1100,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "56",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = -45,
		["centerY"] = 0,
		["delay"] = 1100,
		["endValue"] = -45,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}