hebei = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "4",
			["y"] = 0,
			["x"] = 0,
			["name"] = "hall",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/guobiao/hall.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "22",
			["y"] = 478,
			["x"] = 585,
			["name"] = "wutai",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/hebei/wutai.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "24",
			["y"] = 355,
			["x"] = 590,
			["name"] = "chengqiang",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/hebei/chengqiang.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "21",
			["y"] = 403,
			["x"] = 884,
			["name"] = "bandeng",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/hebei/bandeng.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "23",
			["y"] = 412,
			["x"] = 690,
			["name"] = "taohuaji",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/hebei/taohuaji.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			{
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "17",
					["y"] = 115,
					["x"] = 5,
					["name"] = "zuobianzi",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/zuobianzi.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				["visible"] = 1,
				["time"] = "0",
				["resourceId"] = "16",
				["y"] = 0,
				["x"] = 0,
				["name"] = "Node_zuobianzi",
				["xyScale"] = true,
				["height"] = 0,
				["origVisible"] = true,
				["typeName"] = "",
				["width"] = 0,
			},
			{
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "11",
					["y"] = 113,
					["x"] = 10,
					["name"] = "shenti",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/shenti.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "12",
					["y"] = 130,
					["x"] = 110,
					["name"] = "wantoufadeshou",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/wantoufadeshou.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "13",
					["y"] = 120,
					["x"] = 0,
					["name"] = "tidaishou",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/tidaishou.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "14",
					["y"] = 159,
					["x"] = -20,
					["name"] = "daizi",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/daizi.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				["visible"] = 1,
				["time"] = "0",
				["resourceId"] = "10",
				["y"] = 0,
				["x"] = 0,
				["name"] = "shenti",
				["xyScale"] = true,
				["height"] = 0,
				["origVisible"] = true,
				["typeName"] = "",
				["width"] = 0,
			},
			{
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "6",
					["y"] = 70,
					["x"] = 135,
					["name"] = "youbianzi",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/youbianzi.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "9",
					["y"] = 115,
					["x"] = 30,
					["name"] = "zuobinfa",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/zuobinfa.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "5",
					["y"] = 0,
					["x"] = 0,
					["name"] = "toubi",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/toubi.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "19",
					["y"] = 0,
					["x"] = 0,
					["name"] = "touban",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/touban.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "20",
					["y"] = 0,
					["x"] = 0,
					["name"] = "toukai",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/toukai.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "8",
					["y"] = 115,
					["x"] = 35,
					["name"] = "erduo",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/erduo.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "18",
					["y"] = 75,
					["x"] = 110,
					["name"] = "beiwandetoufa",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/hebei/beiwandetoufa.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				["visible"] = 1,
				["time"] = "0",
				["width"] = 0,
				["y"] = 0,
				["x"] = 0,
				["name"] = "tou",
				["resourceId"] = "3",
				["height"] = 0,
				["origVisible"] = true,
				["typeName"] = "",
				["xyScale"] = true,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "25",
				["y"] = 300,
				["x"] = 15,
				["name"] = "Image_bufferly_l",
				["origVisible"] = true,
				["height"] = 38,
				["file"] = {
					"animation/bufferfly/butterfly0001.png",
					"animation/bufferfly/butterfly0002.png",
					"animation/bufferfly/butterfly0003.png",
					"animation/bufferfly/butterfly0004.png",
				},
				["typeName"] = "AnimFrame",
				["width"] = 37,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "26",
				["y"] = 245,
				["x"] = 140,
				["name"] = "Image_bufferly_s_1",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = {
					"animation/bufferfly/butterfly_small0001.png",
					"animation/bufferfly/butterfly_small0002.png",
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "27",
				["y"] = 80,
				["x"] = 130,
				["name"] = "Image_bufferly_s_2",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = {
					"animation/bufferfly/butterfly_small0001.png",
					"animation/bufferfly/butterfly_small0002.png",
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "28",
				["y"] = 180,
				["x"] = -80,
				["name"] = "Image_tail_l",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = {
					"animation/tail_l/tail0006.png",
					"animation/tail_l/tail0010.png",
					"animation/tail_l/tail0014.png",
					"animation/tail_l/tail0018.png",
					"animation/tail_l/tail0022.png",
					"animation/tail_l/tail0026.png",
					"animation/tail_l/tail0030.png",
					"animation/tail_l/tail0034.png",
					"animation/tail_l/tail0038.png",
					"animation/tail_l/tail0042.png",
					"animation/tail_l/tail0046.png",
					"animation/tail_l/tail0050.png",
					"animation/tail_l/tail0054.png",
					"animation/tail_l/tail0058.png",
					"animation/tail_l/tail0062.png",
					"animation/tail_l/tail0066.png",
					"animation/tail_l/tail0070.png",
					"animation/tail_l/tail0074.png",
					"animation/tail_l/tail0078.png",
					"animation/tail_l/tail0082.png",
					"animation/tail_l/tail0086.png",
					"animation/tail_l/tail0090.png",
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "29",
				["y"] = 200,
				["x"] = 140,
				["name"] = "Image_tail_s_1",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = {
					"animation/tail_s/tail0016.png",
					"animation/tail_s/tail0020.png",
					"animation/tail_s/tail0024.png",
					"animation/tail_s/tail0028.png",
					"animation/tail_s/tail0032.png",
					"animation/tail_s/tail0036.png",
					"animation/tail_s/tail0040.png",
					"animation/tail_s/tail0044.png",
					"animation/tail_s/tail0048.png",
					"animation/tail_s/tail0052.png",
					"animation/tail_s/tail0056.png",
					"animation/tail_s/tail0060.png",
					"animation/tail_s/tail0064.png",
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["resourceId"] = "30",
				["y"] = 20,
				["x"] = 125,
				["name"] = "Image_tail_s_2",
				["origVisible"] = true,
				["height"] = 0,
				["file"] = {
					"animation/tail_s/tail0016.png",
					"animation/tail_s/tail0020.png",
					"animation/tail_s/tail0024.png",
					"animation/tail_s/tail0028.png",
					"animation/tail_s/tail0032.png",
					"animation/tail_s/tail0036.png",
					"animation/tail_s/tail0040.png",
					"animation/tail_s/tail0044.png",
					"animation/tail_s/tail0048.png",
					"animation/tail_s/tail0052.png",
					"animation/tail_s/tail0056.png",
					"animation/tail_s/tail0060.png",
					"animation/tail_s/tail0064.png",
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["width"] = 0,
			["y"] = 132,
			["x"] = 1005,
			["name"] = "body",
			["resourceId"] = "2",
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["xyScale"] = true,
		},
		["visible"] = 1,
		["time"] = "0",
		["width"] = 0,
		["y"] = 0,
		["x"] = 0,
		["name"] = "Relat",
		["resourceId"] = "1",
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["xyScale"] = false,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "4",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 200,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "8",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "11",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "12",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 30,
		["startValue"] = -45,
		["centerY"] = 3,
		["delay"] = 0,
		["endValue"] = -45,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "17",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "17",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 52,
		["startValue"] = -20,
		["centerY"] = 2,
		["delay"] = 200,
		["endValue"] = 20,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 1000,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 19,
		["startValue"] = 20,
		["centerY"] = 4,
		["delay"] = 0,
		["endValue"] = 20,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -236,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 0,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 6,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 200,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -6,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 5,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 600,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "17",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 52,
		["startValue"] = 0,
		["centerY"] = 2,
		["delay"] = 400,
		["endValue"] = -30,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "17",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 52,
		["startValue"] = 0,
		["centerY"] = 2,
		["delay"] = 500,
		["endValue"] = 20,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "17",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 52,
		["startValue"] = 0,
		["centerY"] = 2,
		["delay"] = 700,
		["endValue"] = -20,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 30,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 200,
		["endValue"] = 80,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 30,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 400,
		["endValue"] = -50,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 30,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 600,
		["endValue"] = 20,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 30,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 700,
		["endValue"] = -20,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 30,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 900,
		["endValue"] = 15,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 30,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 1100,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 33,
		["startValue"] = 0,
		["centerY"] = 82,
		["delay"] = 200,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 33,
		["startValue"] = 0,
		["centerY"] = 82,
		["delay"] = 400,
		["endValue"] = 10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 33,
		["startValue"] = 0,
		["centerY"] = 82,
		["delay"] = 600,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "12",
		["duration"] = 500,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 21,
		["startValue"] = 0,
		["centerY"] = 89,
		["delay"] = 1300,
		["endValue"] = 10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "12",
		["duration"] = 500,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 21,
		["startValue"] = 0,
		["centerY"] = 89,
		["delay"] = 1800,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 500,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 15,
		["startValue"] = 0,
		["centerY"] = 2,
		["delay"] = 1300,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 500,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 15,
		["startValue"] = 0,
		["centerY"] = 2,
		["delay"] = 1800,
		["endValue"] = 10,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 500,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.100,
		["centerY"] = 2,
		["delay"] = 1300,
		["centerX"] = 15,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 500,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.900,
		["centerY"] = 2,
		["delay"] = 1800,
		["centerX"] = 15,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 200,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 40,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 30,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 340,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 30,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 370,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 850,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 450,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1350,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 1050,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1450,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 2500,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 2550,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 2600,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 50,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 2650,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 4,
		["startValue"] = -20,
		["centerY"] = 4,
		["delay"] = 0,
		["endValue"] = -20,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 4,
		["startValue"] = 0,
		["centerY"] = 4,
		["delay"] = 200,
		["endValue"] = 35,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 4,
		["startValue"] = 0,
		["centerY"] = 4,
		["delay"] = 400,
		["endValue"] = -30,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 4,
		["startValue"] = 0,
		["centerY"] = 4,
		["delay"] = 600,
		["endValue"] = 25,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 4,
		["startValue"] = 0,
		["centerY"] = 4,
		["delay"] = 700,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.200,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 0.400,
		["startValueX"] = 0.700,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 125,
		["delay"] = 0,
		["centerX"] = 51,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.750,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 300,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.750,
		["centerY"] = 125,
		["delay"] = 200,
		["centerX"] = 51,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.130,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.130,
		["centerY"] = 125,
		["delay"] = 500,
		["centerX"] = 51,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.980,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.980,
		["centerY"] = 125,
		["delay"] = 600,
		["centerX"] = 51,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0.200,
		["delay"] = 0,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 0.500,
		["startValueX"] = 0.500,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.300,
		["centerY"] = 133,
		["delay"] = 200,
		["centerX"] = 56,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.770,
		["centerY"] = 133,
		["delay"] = 300,
		["centerX"] = 56,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 133,
		["delay"] = 400,
		["centerX"] = 56,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.830,
		["centerY"] = 133,
		["delay"] = 500,
		["centerX"] = 56,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.030,
		["centerY"] = 133,
		["delay"] = 600,
		["centerX"] = 56,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 200,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 0.500,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 169,
		["delay"] = 300,
		["centerX"] = 163,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.750,
		["centerY"] = 169,
		["delay"] = 500,
		["centerX"] = 163,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.100,
		["centerY"] = 169,
		["delay"] = 600,
		["centerX"] = 163,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 300,
		["endValue"] = 1,
	},
	{
		["num"] = 4,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 100,
		["delay"] = 400,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -100,
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 1000,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = -100,
		["startValueY"] = 0,
		["delay"] = 400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = 90,
		["centerY"] = 0,
		["delay"] = 1400,
		["endValue"] = 90,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -60,
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 1900,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = -40,
		["startValueY"] = 0,
		["delay"] = 1400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 500,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 2800,
		["endValue"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 50,
		["delay"] = 400,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 50,
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 2000,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = -100,
		["startValueY"] = 0,
		["delay"] = 400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 400,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 400,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 2000,
		["endValue"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 40,
		["delay"] = 300,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -20,
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 1800,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = -110,
		["startValueY"] = 0,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = -45,
		["centerY"] = 0,
		["delay"] = 300,
		["endValue"] = -45,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 300,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 300,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 1800,
		["endValue"] = 0,
	},
	{
		["num"] = 23,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "28",
		["duration"] = 3700,
		["delay"] = 600,
		["animType"] = 0,
	},
	{
		["num"] = 14,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "29",
		["duration"] = 1800,
		["delay"] = 1300,
		["animType"] = 0,
	},
	{
		["num"] = 14,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "30",
		["duration"] = 2700,
		["delay"] = 900,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "30",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["period"] = "nil",
		["centerX"] = 0,
		["startValue"] = -45,
		["centerY"] = 0,
		["delay"] = 900,
		["endValue"] = -45,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 133,
		["delay"] = 3200,
		["centerX"] = 56,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0,
		["centerY"] = 133,
		["delay"] = 3300,
		["centerX"] = 56,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3300,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.500,
		["centerY"] = 169,
		["delay"] = 3300,
		["centerX"] = 163,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0,
		["centerY"] = 169,
		["delay"] = 3400,
		["centerX"] = 163,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3400,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.100,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.100,
		["centerY"] = 125,
		["delay"] = 3300,
		["centerX"] = 51,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0,
		["centerY"] = 125,
		["delay"] = 3400,
		["centerX"] = 51,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 10,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3200,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -220,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3400,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3400,
		["endValue"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}