hebei_bufferly = {
	{
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "25",
				["y"] = 300,
				["x"] = 15,
				["name"] = "Image_bufferly_l",
				["filter"] = 1,
				["height"] = 38,
				["file"] = {
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "butterfly0001.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "butterfly0002.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "butterfly0003.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "butterfly0004.png",
					},
				},
				["typeName"] = "AnimFrame",
				["width"] = 37,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "26",
				["y"] = 245,
				["x"] = 140,
				["name"] = "Image_bufferly_s_1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = {
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "butterfly_small0001.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "butterfly_small0002.png",
					},
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "27",
				["y"] = 80,
				["x"] = 130,
				["name"] = "Image_bufferly_s_2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = {
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "butterfly_small0001.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "butterfly_small0002.png",
					},
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "28",
				["y"] = 180,
				["x"] = -80,
				["name"] = "Image_tail_l",
				["filter"] = 1,
				["height"] = 0,
				["file"] = {
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0006.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0010.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0014.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0018.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0022.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0026.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0030.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0034.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0038.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0042.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0046.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0050.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0054.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0058.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0062.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0066.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0070.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0074.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0078.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0082.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0086.png",
					},
					{
						["packFile"] = "pin_map/tail_pin.lua",
						["path"] = "tail0090.png",
					},
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "29",
				["y"] = 200,
				["x"] = 140,
				["name"] = "Image_tail_s_1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = {
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0016.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0020.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0024.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0028.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0032.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0036.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0040.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0044.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0048.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0052.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0056.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0060.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0064.png",
					},
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "30",
				["y"] = 20,
				["x"] = 125,
				["name"] = "Image_tail_s_2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = {
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0016.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0020.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0024.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0028.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0032.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0036.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0040.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0044.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0048.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0052.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0056.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0060.png",
					},
					{
						["packFile"] = "pin_map/hebeientergril_pin.lua",
						["path"] = "tail0064.png",
					},
				},
				["typeName"] = "AnimFrame",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["width"] = 0,
			["y"] = 0,
			["x"] = 0,
			["name"] = "body",
			["filter"] = 1,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["resourceId"] = "2",
		},
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["resourceId"] = "1",
		["y"] = 0,
		["x"] = 0,
		["name"] = "Relat",
		["filter"] = 1,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["width"] = 0,
	},
	{
		["num"] = 4,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 100,
		["delay"] = 400,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -100,
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 1000,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = -100,
		["delay"] = 400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 90,
		["centerY"] = 0,
		["delay"] = 1400,
		["endValue"] = 90,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -60,
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 1900,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = -40,
		["delay"] = 1400,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "25",
		["duration"] = 500,
		["delay"] = 2800,
		["animType"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 50,
		["delay"] = 400,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 50,
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 2000,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = -100,
		["delay"] = 400,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 200,
		["delay"] = 400,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "26",
		["duration"] = 400,
		["delay"] = 2000,
		["animType"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 40,
		["delay"] = 300,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -20,
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 1800,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = -110,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = -45,
		["centerY"] = 0,
		["delay"] = 300,
		["endValue"] = -45,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 200,
		["delay"] = 300,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "27",
		["duration"] = 300,
		["delay"] = 1800,
		["animType"] = 0,
	},
	{
		["num"] = 22,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "28",
		["duration"] = 3700,
		["delay"] = 600,
		["animType"] = 0,
	},
	{
		["num"] = 13,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "29",
		["duration"] = 1800,
		["delay"] = 1300,
		["animType"] = 0,
	},
	{
		["num"] = 13,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "30",
		["duration"] = 2700,
		["delay"] = 900,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "30",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = -45,
		["centerY"] = 0,
		["delay"] = 900,
		["endValue"] = -45,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}