left_oppo = {
	{
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = true,
		["origVisible"] = true,
		["resourceId"] = "1",
		["y"] = 0,
		["x"] = 0,
		["name"] = "left_seq",
		["filter"] = 1,
		["height"] = 369,
		["file"] = {
			{
				["packFile"] = "qnPlist/left_pin.lua",
				["path"] = "left0001.png",
			},
			{
				["packFile"] = "qnPlist/left_pin.lua",
				["path"] = "left0005.png",
			},
			{
				["packFile"] = "qnPlist/left_pin.lua",
				["path"] = "left0007.png",
			},
			{
				["packFile"] = "qnPlist/left_pin.lua",
				["path"] = "left0009.png",
			},
			{
				["packFile"] = "qnPlist/left_pin.lua",
				["path"] = "left0011.png",
			},
			{
				["packFile"] = "qnPlist/left_pin.lua",
				["path"] = "left0013.png",
			},
		},
		["typeName"] = "AnimFrame",
		["width"] = 512,
	},
	{
		["num"] = 7,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "1",
		["duration"] = 1000,
		["delay"] = 0,
		["animType"] = 0,
	},
	{
		["startValueX"] = 0.700,
		["endValueX"] = 0.700,
		["id"] = "1",
		["duration"] = 1000,
		["animType"] = 0,
		["endValueY"] = 0.700,
		["startValueY"] = 0.700,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}