loadingAnim = {
	{
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["origVisible"] = true,
		["resourceId"] = "1",
		["y"] = 200,
		["x"] = 100,
		["name"] = "img_icon",
		["filter"] = 1,
		["height"] = 0,
		["file"] = "kwx_tanKuang/loading/img_icon.png",
		["typeName"] = "Image",
		["width"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "1",
		["duration"] = 1000,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 1.100,
		["type"] = "AtomAnimScale",
		["centerType"] = 0,
		["centerY"] = 49,
		["delay"] = 0,
		["centerX"] = 114,
	},
	{
		["startValueX"] = 1.100,
		["endValueX"] = 0.900,
		["id"] = "1",
		["duration"] = 1000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 0,
		["centerY"] = 49,
		["delay"] = 1000,
		["centerX"] = 114,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "1",
		["duration"] = 1000,
		["animType"] = 0,
		["period"] = 0.300,
		["endValueY"] = -20,
		["startValueY"] = 0,
		["delay"] = 1000,
		["startValueX"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}