lose = {
	{
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "9",
				["y"] = 10,
				["x"] = 100,
				["name"] = "ink0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/ink0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "10",
				["y"] = 10,
				["x"] = 100,
				["name"] = "ink0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/ink0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "7",
				["y"] = 0,
				["x"] = 0,
				["name"] = "lose0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/lose/lose0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "8",
				["y"] = 0,
				["x"] = 0,
				["name"] = "lose0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/lose/lose0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "13",
				["y"] = 0,
				["x"] = 0,
				["name"] = "lose0003",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/lose/lose0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["width"] = 364,
			["y"] = 0,
			["x"] = 0,
			["name"] = "Node_lose_text",
			["filter"] = 1,
			["height"] = 142,
			["origVisible"] = true,
			["typeName"] = "",
			["resourceId"] = "6",
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "12",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Image_wind_seq",
			["filter"] = 1,
			["height"] = 0,
			["file"] = {
				{
					["path"] = "animation/lose/wind0001.png",
				},
				{
					["path"] = "animation/lose/wind0007.png",
				},
				{
					["path"] = "animation/lose/wind0013.png",
				},
				{
					["path"] = "animation/lose/wind0019.png",
				},
				{
					["path"] = "animation/lose/wind0025.png",
				},
				{
					["path"] = "animation/lose/wind0031.png",
				},
				{
					["path"] = "animation/lose/wind0037.png",
				},
				{
					["path"] = "animation/lose/wind0043.png",
				},
				{
					["path"] = "animation/lose/wind0049.png",
				},
				{
					["path"] = "animation/lose/wind0055.png",
				},
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["resourceId"] = "5",
		["y"] = 200,
		["x"] = 200,
		["name"] = "Node_Relat",
		["filter"] = 1,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["width"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "9",
		["duration"] = 2400,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "10",
		["duration"] = 2400,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 200,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "7",
		["duration"] = 2400,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "7",
		["duration"] = 200,
		["animType"] = 2,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = -2,
		["centerY"] = 0,
		["delay"] = 400,
		["endValue"] = 2,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "7",
		["duration"] = 1000,
		["delay"] = 1400,
		["animType"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "8",
		["duration"] = 2400,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "8",
		["duration"] = 200,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 1000,
		["animType"] = 2,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 1400,
		["startValueX"] = 0,
	},
	{
		["startValueX"] = 2,
		["endValueX"] = 1,
		["id"] = "6",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 2,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.500,
		["id"] = "6",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1.500,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "6",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 300,
		["centerX"] = 0,
	},
	{
		["num"] = 10,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "12",
		["duration"] = 2400,
		["delay"] = 0,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 1000,
		["delay"] = 2400,
		["animType"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}