moneybag = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "2",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Image_moneybag_seq",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = {
				"animation/moneybag/moneybag00010001.png",
				"animation/moneybag/moneybag00010005.png",
				"animation/moneybag/moneybag00010009.png",
				"animation/moneybag/moneybag00010013.png",
				"animation/moneybag/moneybag00010017.png",
				"animation/moneybag/moneybag00010021.png",
				"animation/moneybag/moneybag00010025.png",
				"animation/moneybag/moneybag00010029.png",
				"animation/moneybag/moneybag00010033.png",
				"animation/moneybag/moneybag00010037.png",
				"animation/moneybag/moneybag00010041.png",
				"animation/moneybag/moneybag00010045.png",
				"animation/moneybag/moneybag00010049.png",
				"animation/moneybag/moneybag00010053.png",
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		["visible"] = 1,
		["time"] = "0",
		["resourceId"] = "1",
		["y"] = 0,
		["x"] = 0,
		["name"] = "Node_Relat",
		["xyScale"] = false,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["width"] = 0,
	},
	{
		["num"] = 14,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 2300,
		["delay"] = 0,
		["animType"] = 1,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}