resultless = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "15",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Image_moji_seq",
			["filter"] = 1,
			["height"] = 0,
			["file"] = {
				{
					["path"] = "animation/resultless/mo0001.png",
				},
				{
					["path"] = "animation/resultless/mo0002.png",
				},
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "12",
				["y"] = 0,
				["x"] = 0,
				["name"] = "ink0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/ink0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "13",
				["y"] = 0,
				["x"] = 0,
				["name"] = "ink0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/ink0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "11",
			["y"] = 20,
			["x"] = 80,
			["name"] = "Node_moji",
			["filter"] = 1,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["origVisible"] = true,
			["resourceId"] = "6",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Image_seq",
			["filter"] = 1,
			["height"] = 161,
			["file"] = {
				{
					["path"] = "animation/resultless/resultless3.png",
				},
				{
					["path"] = "animation/resultless/resultless4.png",
				},
			},
			["typeName"] = "AnimFrame",
			["width"] = 288,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "4",
				["y"] = 0,
				["x"] = 0,
				["name"] = "resultless1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/resultless/resultless1.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "5",
				["y"] = 0,
				["x"] = 0,
				["name"] = "resultless2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/resultless/resultless2.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "3",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Node_resultless",
			["filter"] = 1,
			["height"] = 161,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 288,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "10",
				["y"] = 0,
				["x"] = 0,
				["name"] = "leaf0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/resultless/leaf0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "9",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Node_leaf",
			["filter"] = 1,
			["height"] = 169,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 289,
		},
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["width"] = 0,
		["y"] = 0,
		["x"] = 0,
		["name"] = "Node_relat",
		["filter"] = 1,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["resourceId"] = "1",
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 100,
		["delay"] = 800,
		["animType"] = 2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 300,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 800,
		["endValue"] = -50,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 1100,
		["endValue"] = 90,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 100,
		["delay"] = 1100,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "12",
		["duration"] = 1800,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 100,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 1800,
		["animType"] = 0,
		["startValueY"] = 0,
		["endValueY"] = 0,
		["delay"] = 100,
		["startValueX"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 300,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "11",
		["duration"] = 0,
		["delay"] = 800,
		["animType"] = 0,
	},
	{
		["num"] = 2,
		["type"] = "AtomAnimFrame",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 200,
		["delay"] = 800,
		["animType"] = 1,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 300,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 800,
		["endValue"] = -60,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 700,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 1100,
		["endValue"] = 1080,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0,
		["id"] = "6",
		["duration"] = 700,
		["animType"] = 0,
		["endValueY"] = 0,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1100,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0.300,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "6",
		["duration"] = 700,
		["delay"] = 1100,
		["animType"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "4",
		["duration"] = 1000,
		["animType"] = 2,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "4",
		["duration"] = 300,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 800,
		["endValue"] = -50,
	},
	{
		["endValue"] = 0.500,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "4",
		["duration"] = 300,
		["delay"] = 800,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0.500,
		["easeType"] = "Nil",
		["id"] = "4",
		["duration"] = 700,
		["delay"] = 1100,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "4",
		["duration"] = 700,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 1100,
		["endValue"] = 720,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0,
		["id"] = "4",
		["duration"] = 700,
		["animType"] = 0,
		["endValueY"] = 0,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.200,
		["id"] = "4",
		["duration"] = 900,
		["animType"] = 0,
		["endValueY"] = 1.200,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 800,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "5",
		["duration"] = 1000,
		["animType"] = 2,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["endValue"] = 0.500,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 100,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 100,
		["delay"] = 200,
		["animType"] = 0,
	},
	{
		["startValueX"] = 2.500,
		["endValueX"] = 0.900,
		["id"] = "3",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 2.500,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 200,
		["centerX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 1000,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 500,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = -90,
		["centerY"] = 0,
		["delay"] = 100,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 400,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 800,
		["endValue"] = 360,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 400,
		["delay"] = 800,
		["animType"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}