shake = {
	{
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["resourceId"] = "1",
		["y"] = 100,
		["x"] = 100,
		["name"] = "scenc_right_decorate2",
		["origVisible"] = true,
		["height"] = 0,
		["file"] = "common/scenc_right_decorate2.png",
		["typeName"] = "Image",
		["width"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "1",
		["duration"] = 1000,
		["animType"] = 2,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 22,
		["startValue"] = -10,
		["centerY"] = 0,
		["delay"] = 0,
		["endValue"] = 10,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}