shanghai = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "3",
			["y"] = 0,
			["x"] = 0,
			["name"] = "hall",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/guobiao/hall.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "20",
			["y"] = 480,
			["x"] = 585,
			["name"] = "shanghaiwutai",
			["origVisible"] = true,
			["height"] = 134,
			["file"] = "animation/shanghai/shanghaiwutai.png",
			["typeName"] = "Image",
			["width"] = 438,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "24",
			["y"] = 340,
			["x"] = 635,
			["name"] = "pingfeng",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/shanghai/pingfeng.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "22",
			["y"] = 470,
			["x"] = 645,
			["name"] = "bandeng",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/shanghai/bandeng.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		{
			{
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "10",
					["y"] = 68,
					["x"] = -18,
					["name"] = "zuofa",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/zuofa.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "5",
					["y"] = 0,
					["x"] = 0,
					["name"] = "touban",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/touban.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "18",
					["y"] = 0,
					["x"] = 0,
					["name"] = "toutai",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/toutai.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "19",
					["y"] = 0,
					["x"] = 0,
					["name"] = "toubi",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/toubi.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "9",
					["y"] = 25,
					["x"] = 80,
					["name"] = "youfa",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/youfa.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "11",
					["y"] = 110,
					["x"] = 15,
					["name"] = "zuibi",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/zuibi.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "16",
					["y"] = 110,
					["x"] = 15,
					["name"] = "zuiban",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/zuiban.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "17",
					["y"] = 110,
					["x"] = 15,
					["name"] = "zuikai",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/zuikai.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				["visible"] = 1,
				["time"] = "0",
				["width"] = 0,
				["y"] = 0,
				["x"] = 0,
				["name"] = "tou",
				["resourceId"] = "4",
				["height"] = 0,
				["origVisible"] = true,
				["typeName"] = "",
				["xyScale"] = true,
			},
			{
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "13",
					["y"] = 0,
					["x"] = 0,
					["name"] = "shenti",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/shenti.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				{
					["visible"] = 1,
					["time"] = "0",
					["xyScale"] = true,
					["resourceId"] = "14",
					["y"] = 150,
					["x"] = 130,
					["name"] = "bao",
					["origVisible"] = true,
					["height"] = 0,
					["file"] = "animation/shanghai/bao.png",
					["typeName"] = "Image",
					["width"] = 0,
				},
				["visible"] = 1,
				["time"] = "0",
				["resourceId"] = "12",
				["y"] = 105,
				["x"] = 35,
				["name"] = "shenti",
				["xyScale"] = true,
				["height"] = 0,
				["origVisible"] = true,
				["typeName"] = "",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["resourceId"] = "2",
			["y"] = 120,
			["x"] = 950,
			["name"] = "Node_Body",
			["xyScale"] = true,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 0,
		},
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "23",
			["y"] = 232,
			["x"] = 708,
			["name"] = "mai",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = "animation/shanghai/mai.png",
			["typeName"] = "Image",
			["width"] = 0,
		},
		["visible"] = 1,
		["time"] = "0",
		["width"] = 0,
		["y"] = 0,
		["x"] = 0,
		["name"] = "Relat",
		["resourceId"] = "1",
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["xyScale"] = false,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "3",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 900,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "11",
		["duration"] = 800,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "13",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -180,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 300,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0.500,
		["delay"] = 0,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 120,
		["startValue"] = 0,
		["centerY"] = 420,
		["delay"] = 300,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 120,
		["startValue"] = 0,
		["centerY"] = 420,
		["delay"] = 500,
		["endValue"] = 4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 120,
		["startValue"] = 0,
		["centerY"] = 420,
		["delay"] = 600,
		["endValue"] = -1,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 120,
		["startValue"] = 0,
		["centerY"] = 420,
		["delay"] = 700,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 27,
		["startValue"] = 0,
		["centerY"] = 1,
		["delay"] = 300,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 27,
		["startValue"] = 0,
		["centerY"] = 1,
		["delay"] = 500,
		["endValue"] = 8,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 27,
		["startValue"] = 0,
		["centerY"] = 1,
		["delay"] = 600,
		["endValue"] = -4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 27,
		["startValue"] = 0,
		["centerY"] = 1,
		["delay"] = 700,
		["endValue"] = 4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 32,
		["startValue"] = 0,
		["centerY"] = 9,
		["delay"] = 300,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 32,
		["startValue"] = 0,
		["centerY"] = 9,
		["delay"] = 500,
		["endValue"] = 5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 32,
		["startValue"] = 0,
		["centerY"] = 9,
		["delay"] = 600,
		["endValue"] = -4,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 32,
		["startValue"] = 0,
		["centerY"] = 9,
		["delay"] = 700,
		["endValue"] = 4,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "16",
		["duration"] = 500,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 800,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "17",
		["duration"] = 2100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 900,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1000,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1100,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 2200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1200,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "4",
		["duration"] = 700,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 104,
		["startValue"] = 0,
		["centerY"] = 153,
		["delay"] = 1300,
		["endValue"] = 5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "4",
		["duration"] = 1000,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 104,
		["startValue"] = 0,
		["centerY"] = 153,
		["delay"] = 2000,
		["endValue"] = -6,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 700,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 32,
		["startValue"] = 0,
		["centerY"] = 9,
		["delay"] = 2000,
		["endValue"] = -2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "9",
		["duration"] = 300,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 32,
		["startValue"] = 0,
		["centerY"] = 9,
		["delay"] = 2700,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 500,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 27,
		["startValue"] = 0,
		["centerY"] = 1,
		["delay"] = 2000,
		["endValue"] = -2,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "10",
		["duration"] = 500,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 27,
		["startValue"] = 0,
		["centerY"] = 1,
		["delay"] = 2500,
		["endValue"] = 2,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "16",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3400,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 50,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3450,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3500,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 300,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3600,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 200,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 12,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 300,
		["endValue"] = -10,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 12,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 500,
		["endValue"] = 9,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 12,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 600,
		["endValue"] = -5,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "14",
		["duration"] = 100,
		["animType"] = 0,
		["centerType"] = 2,
		["period"] = "nil",
		["centerX"] = 12,
		["startValue"] = 0,
		["centerY"] = 3,
		["delay"] = 700,
		["endValue"] = 5,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.500,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 0.200,
		["startValueX"] = 0.200,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.500,
		["centerY"] = 70,
		["delay"] = 200,
		["centerX"] = 55,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.660,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1.500,
		["startValueX"] = 1.500,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.660,
		["centerY"] = 70,
		["delay"] = 400,
		["centerX"] = 55,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 1000,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 500,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 0,
		["delay"] = 200,
		["endValue"] = 1,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.300,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 0.100,
		["startValueX"] = 0.100,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.300,
		["centerY"] = 319,
		["delay"] = 700,
		["centerX"] = 87,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.760,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.760,
		["centerY"] = 319,
		["delay"] = 900,
		["centerX"] = 87,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 2300,
		["animType"] = 2,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 1000,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.200,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 319,
		["delay"] = 3300,
		["centerX"] = 87,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "23",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0,
		["centerY"] = 319,
		["delay"] = 3500,
		["centerX"] = 87,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.200,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 70,
		["delay"] = 3300,
		["centerX"] = 55,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0,
		["centerY"] = 70,
		["delay"] = 3500,
		["centerX"] = 55,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3500,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 10,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 100,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3600,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = -300,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 3700,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3700,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimAlpha",
		["easeType"] = "Nil",
		["id"] = "20",
		["duration"] = 200,
		["animType"] = 0,
		["period"] = "nil",
		["startValue"] = 1,
		["delay"] = 3600,
		["endValue"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.200,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 0.100,
		["startValueX"] = 0.100,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 171,
		["delay"] = 0,
		["centerX"] = 114,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0.830,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0.830,
		["centerY"] = 171,
		["delay"] = 200,
		["centerX"] = 114,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 3000,
		["animType"] = 0,
		["period"] = "nil",
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 300,
		["startValueX"] = 0,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 1.200,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 200,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 1.200,
		["centerY"] = 171,
		["delay"] = 3300,
		["centerX"] = 114,
	},
	{
		["type"] = "AtomAnimScale",
		["endValueX"] = 0,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 100,
		["animType"] = 0,
		["startValueY"] = 1,
		["startValueX"] = 1,
		["period"] = "nil",
		["centerType"] = 2,
		["endValueY"] = 0,
		["centerY"] = 171,
		["delay"] = 3500,
		["centerX"] = 141,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}