startGameBtnMagnify = {
	{
		{
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "2",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Image_seq",
			["origVisible"] = true,
			["height"] = 0,
			["file"] = {
				"animation/magnify/magnify0001.png",
				"animation/magnify/magnify0003.png",
				"animation/magnify/magnify0005.png",
				"animation/magnify/magnify0007.png",
				"animation/magnify/magnify0009.png",
				"animation/magnify/magnify0011.png",
				"animation/magnify/magnify0013.png",
			},
			["typeName"] = "AnimFrame",
			["width"] = 0,
		},
		["visible"] = 1,
		["time"] = "0",
		["resourceId"] = "1",
		["y"] = 0,
		["x"] = 0,
		["name"] = "Node_magnify",
		["xyScale"] = false,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["width"] = 0,
	},
	{
		["num"] = 7,
		["type"] = "AtomAnimFrame",
		["period"] = "nil",
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 500,
		["delay"] = 0,
		["animType"] = 2,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}