test = {
	{
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["origVisible"] = true,
		["resourceId"] = "2",
		["y"] = 0,
		["x"] = 0,
		["name"] = "finger",
		["filter"] = 1,
		["height"] = 0,
		["file"] = "room/finger.png",
		["typeName"] = "Image",
		["width"] = 0,
	},
	{
		["type"] = "AtomAnimTranslate",
		["endValueX"] = 299,
		["easeType"] = "Nil",
		["id"] = "2",
		["duration"] = 1000,
		["animType"] = 0,
		["period"] = 0.300,
		["endValueY"] = 0,
		["startValueY"] = 0,
		["delay"] = 0,
		["startValueX"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}