upgrade = {
	{
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "32",
				["y"] = 0,
				["x"] = 0,
				["name"] = "zhuan",
				["filter"] = 1,
				["height"] = 800,
				["file"] = "animation/upgrade/zhuan.png",
				["typeName"] = "Image",
				["width"] = 800,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "31",
			["y"] = -400,
			["x"] = -100,
			["name"] = "Node_zhuan",
			["filter"] = 1,
			["height"] = 800,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 800,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "17",
				["y"] = 0,
				["x"] = 0,
				["name"] = "trumpet0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/trumpet0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "18",
				["y"] = 0,
				["x"] = 0,
				["name"] = "trumpet0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/trumpet0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "16",
			["y"] = -85,
			["x"] = 70,
			["name"] = "Node_trumpets_left2",
			["filter"] = 1,
			["height"] = 180,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 180,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "13",
				["y"] = 0,
				["x"] = 0,
				["name"] = "trumpet0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/trumpet0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "15",
				["y"] = 0,
				["x"] = 0,
				["name"] = "trumpet0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/trumpet0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "12",
			["y"] = -85,
			["x"] = 100,
			["name"] = "Node_trumpets_left1",
			["filter"] = 1,
			["height"] = 180,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 180,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "23",
				["y"] = 0,
				["x"] = 0,
				["name"] = "trumpet0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/trumpet0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "24",
				["y"] = 0,
				["x"] = 0,
				["name"] = "trumpet0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/trumpet0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "22",
			["y"] = -80,
			["x"] = 215,
			["name"] = "Node_trumpets_right2",
			["filter"] = 1,
			["height"] = 180,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 180,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "20",
				["y"] = 0,
				["x"] = 0,
				["name"] = "trumpet0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/trumpet0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "21",
				["y"] = 0,
				["x"] = 0,
				["name"] = "trumpet0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/trumpet0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "19",
			["y"] = -80,
			["x"] = 185,
			["name"] = "Node_trumpets_right1",
			["filter"] = 1,
			["height"] = 180,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 180,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "10",
				["y"] = 0,
				["x"] = 0,
				["name"] = "star0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/star0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "11",
				["y"] = 0,
				["x"] = 0,
				["name"] = "star0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/star0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "9",
			["y"] = -150,
			["x"] = 190,
			["name"] = "Node_star",
			["filter"] = 1,
			["height"] = 0,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 0,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "4",
				["y"] = 0,
				["x"] = 0,
				["name"] = "riband0001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/riband0001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "5",
				["y"] = 0,
				["x"] = 0,
				["name"] = "riband0002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/riband0002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "3",
			["y"] = 0,
			["x"] = 0,
			["name"] = "Node_riband",
			["filter"] = 1,
			["height"] = 180,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 640,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "7",
				["y"] = 0,
				["x"] = 0,
				["name"] = "text001",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/text001.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "8",
				["y"] = 0,
				["x"] = 0,
				["name"] = "text002",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/text002.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "6",
			["y"] = 45,
			["x"] = 200,
			["name"] = "Node_upgrade_text",
			["filter"] = 1,
			["height"] = 100,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 210,
		},
		{
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "26",
				["y"] = 0,
				["x"] = 0,
				["name"] = "smallstar1",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/smallstar.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "27",
				["y"] = 25,
				["x"] = 180,
				["name"] = "smallstar2",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/smallstar.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "28",
				["y"] = 100,
				["x"] = 115,
				["name"] = "smallstar3",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/smallstar.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			{
				["visible"] = 1,
				["time"] = "0",
				["xyScale"] = true,
				["origVisible"] = true,
				["resourceId"] = "29",
				["y"] = 15,
				["x"] = -125,
				["name"] = "smallstar4",
				["filter"] = 1,
				["height"] = 0,
				["file"] = "animation/upgrade/smallstar.png",
				["typeName"] = "Image",
				["width"] = 0,
			},
			["visible"] = 1,
			["time"] = "0",
			["xyScale"] = true,
			["resourceId"] = "25",
			["y"] = -90,
			["x"] = 210,
			["name"] = "Node_star_flash",
			["filter"] = 1,
			["height"] = 70,
			["origVisible"] = true,
			["typeName"] = "",
			["width"] = 60,
		},
		["visible"] = 1,
		["time"] = "0",
		["xyScale"] = false,
		["width"] = 0,
		["y"] = 0,
		["x"] = 0,
		["name"] = "Node_relati",
		["filter"] = 1,
		["height"] = 0,
		["origVisible"] = true,
		["typeName"] = "",
		["resourceId"] = "1",
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "32",
		["duration"] = 2500,
		["animType"] = 0,
		["centerType"] = 1,
		["centerX"] = 0,
		["startValue"] = 0,
		["centerY"] = 0,
		["delay"] = 500,
		["endValue"] = 260,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "17",
		["duration"] = 2500,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 500,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "18",
		["duration"] = 50,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 550,
		["centerX"] = 157,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "18",
		["duration"] = 50,
		["delay"] = 550,
		["animType"] = 0,
	},
	{
		["startValueX"] = 0.300,
		["endValueX"] = 1.200,
		["id"] = "16",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.200,
		["startValueY"] = 0.300,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 500,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "16",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 600,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "16",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 800,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "13",
		["duration"] = 2600,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 400,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "15",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 400,
		["centerX"] = 157,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 50,
		["delay"] = 450,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "15",
		["duration"] = 200,
		["delay"] = 500,
		["animType"] = 0,
	},
	{
		["startValueX"] = 0.100,
		["endValueX"] = 1,
		["id"] = "12",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 0.100,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 400,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "12",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 500,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "12",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 700,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.900,
		["id"] = "12",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 800,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "23",
		["duration"] = 2500,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 500,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "24",
		["duration"] = 50,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 550,
		["centerX"] = 157,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "24",
		["duration"] = 50,
		["delay"] = 550,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "22",
		["duration"] = 0,
		["animType"] = 0,
		["centerType"] = 2,
		["centerX"] = 157,
		["startValue"] = 90,
		["centerY"] = 155,
		["delay"] = 0,
		["endValue"] = 90,
	},
	{
		["startValueX"] = 0.300,
		["endValueX"] = 1.200,
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.200,
		["startValueY"] = 0.300,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 500,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "22",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 600,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "22",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 800,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "20",
		["duration"] = 2600,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 0,
		["delay"] = 400,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "21",
		["duration"] = 2600,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 0,
		["delay"] = 400,
		["centerX"] = 0,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 50,
		["delay"] = 450,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "21",
		["duration"] = 200,
		["delay"] = 500,
		["animType"] = 0,
	},
	{
		["type"] = "AtomAnimRotate",
		["easeType"] = "Nil",
		["id"] = "19",
		["duration"] = 0,
		["animType"] = 0,
		["centerType"] = 2,
		["centerX"] = 155,
		["startValue"] = 90,
		["centerY"] = 157,
		["delay"] = 0,
		["endValue"] = 90,
	},
	{
		["startValueX"] = 0.100,
		["endValueX"] = 1,
		["id"] = "19",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 0.100,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 400,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "19",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 500,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "19",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 700,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.900,
		["id"] = "19",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 155,
		["delay"] = 800,
		["centerX"] = 157,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "10",
		["duration"] = 2600,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 170,
		["delay"] = 400,
		["centerX"] = 110,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "11",
		["duration"] = 1000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 170,
		["delay"] = 400,
		["centerX"] = 110,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "11",
		["duration"] = 50,
		["delay"] = 450,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "11",
		["duration"] = 100,
		["delay"] = 500,
		["animType"] = 0,
	},
	{
		["startValueX"] = 0.900,
		["endValueX"] = 1.200,
		["id"] = "9",
		["duration"] = 50,
		["animType"] = 0,
		["endValueY"] = 1.200,
		["startValueY"] = 0.500,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 170,
		["delay"] = 400,
		["centerX"] = 110,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "9",
		["duration"] = 50,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 170,
		["delay"] = 450,
		["centerX"] = 110,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "9",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0.720,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 170,
		["delay"] = 500,
		["centerX"] = 110,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "9",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 170,
		["delay"] = 700,
		["centerX"] = 110,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "9",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 2,
		["centerY"] = 170,
		["delay"] = 800,
		["centerX"] = 110,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "4",
		["duration"] = 3000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "5",
		["duration"] = 1000,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 100,
		["delay"] = 100,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 100,
		["delay"] = 200,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "5",
		["duration"] = 200,
		["delay"] = 500,
		["animType"] = 0,
	},
	{
		["startValueX"] = 0,
		["endValueX"] = 0.150,
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.150,
		["startValueY"] = 0,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 0,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 5,
		["id"] = "3",
		["duration"] = 50,
		["animType"] = 0,
		["endValueY"] = 5,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.800,
		["id"] = "3",
		["duration"] = 50,
		["animType"] = 0,
		["endValueY"] = 1.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 150,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.800,
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.800,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 200,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 300,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "3",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 500,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.900,
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 700,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.050,
		["id"] = "3",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.050,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 800,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "7",
		["duration"] = 2600,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 400,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1,
		["id"] = "8",
		["duration"] = 2600,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 400,
		["centerX"] = 0,
	},
	{
		["endValue"] = 1,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 0.500,
		["easeType"] = "Nil",
		["id"] = "8",
		["duration"] = 100,
		["delay"] = 400,
		["animType"] = 0,
	},
	{
		["endValue"] = 0,
		["type"] = "AtomAnimAlpha",
		["startValue"] = 1,
		["easeType"] = "Nil",
		["id"] = "8",
		["duration"] = 200,
		["delay"] = 500,
		["animType"] = 0,
	},
	{
		["startValueX"] = 3,
		["endValueX"] = 1,
		["id"] = "6",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 3,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 400,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "6",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 600,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0.900,
		["id"] = "6",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 0.900,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 700,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 1.100,
		["id"] = "6",
		["duration"] = 100,
		["animType"] = 0,
		["endValueY"] = 1.100,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 800,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 0.500,
		["endValueX"] = 1,
		["id"] = "26",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 0.500,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1000,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0,
		["id"] = "26",
		["duration"] = 300,
		["animType"] = 0,
		["endValueY"] = 0,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1200,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 0.500,
		["endValueX"] = 1,
		["id"] = "27",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 0.500,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1000,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0,
		["id"] = "27",
		["duration"] = 300,
		["animType"] = 0,
		["endValueY"] = 0,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1200,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 0.400,
		["endValueX"] = 1,
		["id"] = "28",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 0.500,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0,
		["id"] = "28",
		["duration"] = 300,
		["animType"] = 0,
		["endValueY"] = 0,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1300,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 0.400,
		["endValueX"] = 1,
		["id"] = "29",
		["duration"] = 300,
		["animType"] = 0,
		["endValueY"] = 1,
		["startValueY"] = 0.500,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1100,
		["centerX"] = 0,
	},
	{
		["startValueX"] = 1,
		["endValueX"] = 0,
		["id"] = "29",
		["duration"] = 200,
		["animType"] = 0,
		["endValueY"] = 0,
		["startValueY"] = 1,
		["type"] = "AtomAnimScale",
		["centerType"] = 1,
		["centerY"] = 0,
		["delay"] = 1400,
		["centerX"] = 0,
	},
	["visible"] = 1,
	["fillParentWidth"] = 0,
	["width"] = 0,
	["y"] = 0,
	["x"] = 0,
	["name"] = "Aircraft",
	["fillParentHeight"] = 0,
	["height"] = 0,
	["typeName"] = "AnimNode",
	["nodeAlign"] = 8,
}