local accountsLayout=
{
	name="accountsLayout",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTop,
	{
		name="view_top",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=200,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="img_title",type=1,typeName="Image",time=0,x=0,y=0,width=592,height=118,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/accounts/img_title.png"
		},
		{
			name="btn_back",type=1,typeName="Button",time=0,x=11,y=18,width=82,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_back.png"
		},
		{
			name="btn_share",type=1,typeName="Button",time=0,x=14,y=5,width=126,height=144,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_room/room_gameOver/btn_share.png"
		}
	},
	{
		name="view_other",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=517,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
		{
			name="img_my",type=1,typeName="Image",time=0,x=0,y=4,width=300,height=350,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="kwx_room/accounts/img_level1.png",
			{
				name="Image11",type=1,typeName="Image",time=0,x=0,y=-51,width=250,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/accounts/img_namebg.png",
				{
					name="text_name1",type=4,typeName="Text",time=0,x=0,y=0,width=104,height=28.55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=28,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[我]]
				}
			},
			{
				name="img_head1",type=1,typeName="Image",time=0,x=0,y=-243,width=198,height=198,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/accounts/img_headK1.png"
			},
			{
				name="Image21",type=1,typeName="Image",time=0,x=111,y=-278,width=80,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_touguan.png"
			},
			{
				name="view_score1",type=0,typeName="View",time=0,x=0,y=-55,width=208,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
			}
		},
		{
			name="img_play2",type=1,typeName="Image",time=0,x=-350,y=4,width=300,height=350,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="kwx_room/accounts/img_level2.png",
			{
				name="Image111",type=1,typeName="Image",time=0,x=0,y=16,width=250,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/accounts/img_namebg.png",
				{
					name="text_name2",type=4,typeName="Text",time=0,x=0,y=0,width=104,height=28.55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=28,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[我]]
				}
			},
			{
				name="img_head2",type=1,typeName="Image",time=0,x=0,y=-184,width=198,height=198,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/accounts/img_headK2.png"
			},
			{
				name="view_score2",type=0,typeName="View",time=0,x=0,y=-55,width=208,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
			}
		},
		{
			name="img_play4",type=1,typeName="Image",time=0,x=350,y=4,width=300,height=350,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="kwx_room/accounts/img_level3.png",
			{
				name="Image1111",type=1,typeName="Image",time=0,x=0,y=69,width=250,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/accounts/img_namebg.png",
				{
					name="text_name3",type=4,typeName="Text",time=0,x=0,y=0,width=104,height=28.55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=28,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[我]]
				}
			},
			{
				name="img_head3",type=1,typeName="Image",time=0,x=0,y=-128,width=198,height=198,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/accounts/img_headK4.png"
			},
			{
				name="view_score3",type=0,typeName="View",time=0,x=0,y=-55,width=208,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
			}
		},
		{
			name="Image25",type=1,typeName="Image",time=0,x=812,y=86,width=40,height=52,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai2.png"
		},
		{
			name="Image26",type=1,typeName="Image",time=0,x=421,y=87,width=40,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai4.png"
		},
		{
			name="Image27",type=1,typeName="Image",time=0,x=825,y=-66,width=40,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai5.png"
		},
		{
			name="Image28",type=1,typeName="Image",time=0,x=151,y=103,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai1.png"
		},
		{
			name="Image29",type=1,typeName="Image",time=0,x=460,y=-64,width=42,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai3.png"
		},
		{
			name="Image31",type=1,typeName="Image",time=0,x=1025,y=-77,width=42,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai3.png"
		},
		{
			name="Image32",type=1,typeName="Image",time=0,x=366,y=-125,width=40,height=52,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai2.png"
		},
		{
			name="Image33",type=1,typeName="Image",time=0,x=843,y=17,width=40,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai5.png"
		},
		{
			name="Image34",type=1,typeName="Image",time=0,x=758,y=-98,width=40,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_room/accounts/img_cai4.png"
		}
	}
}
return accountsLayout;