local buyGoodsLayout=
{
	name="buyGoodsLayout",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,isLuaLocal=0,
	{
		name="img_bg",type=1,typeName="Image",time=0,x=0,y=0,width=632,height=430,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_common/img_tanKuang_small.png",
		{
			name="Text4",type=4,typeName="Text",time=0,x=238,y=31,width=160,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=40,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[购买道具]]
		},
		{
			name="view_goodsShow",type=0,typeName="View",time=0,x=34,y=95,width=566,height=220,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="Image6",type=1,typeName="Image",time=0,x=0,y=0,width=580,height=220,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_common/img_dikuang.png",gridLeft=50,gridRight=50,gridTop=50,gridBottom=50
			},
			{
				name="Image10",type=1,typeName="Image",time=0,x=61,y=33,width=164,height=170,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/img_goods_bg.png",
				{
					name="Image18",type=1,typeName="Image",time=0,x=18,y=108,width=42,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/img_gold.png"
				},
				{
					name="img_goodsMark",type=1,typeName="Image",time=0,x=0,y=-28,width=4,height=12,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/scene_vline.png"
				},
				{
					name="text_goldPrice",type=4,typeName="Text",time=0,x=65,y=116,width=52,height=23.35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=240,colorBlue=34,string=[[20000]]
				}
			},
			{
				name="view_inputNumber",type=0,typeName="View",time=0,x=254,y=37,width=275,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="btn_add",type=1,typeName="Button",time=0,x=218,y=8,width=40,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/btn_add.png"
				},
				{
					name="Image15",type=1,typeName="Image",time=0,x=64,y=8,width=144,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/img_number_bg.png",
					{
						name="editText_number",type=6,typeName="EditText",time=0,x=0,y=0,width=106,height=27,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=0,colorGreen=60,colorBlue=140,string=[[80]]
					}
				},
				{
					name="btn_cut",type=1,typeName="Button",time=0,x=13,y=8,width=40,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/btn_cut.png"
				}
			},
			{
				name="view_totlePrice",type=0,typeName="View",time=0,x=257,y=104,width=256,height=37,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="Text22",type=4,typeName="Text",time=0,x=7,y=5,width=66.65,height=26.65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[总价:]]
				},
				{
					name="text_totlePrice",type=4,typeName="Text",time=0,x=77,y=5,width=158,height=27.65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=240,colorBlue=34,string=[[200000]]
				}
			},
			{
				name="view_curGold",type=0,typeName="View",time=0,x=258,y=145,width=258,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="Text25",type=4,typeName="Text",time=0,x=5,y=5,width=66.65,height=26.65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[现有:]]
				},
				{
					name="text_curGold",type=4,typeName="Text",time=0,x=75,y=4,width=142.35,height=26.65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=240,colorBlue=34,string=[[2000000]]
				}
			}
		},
		{
			name="btn_buy",type=1,typeName="Button",time=0,x=0,y=146,width=240,height=90,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_common/btn_blue_big.png",
			{
				name="Text8",type=4,typeName="Text",time=0,x=0,y=0,width=73.35,height=36.65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=36,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[购买]]
			}
		},
		{
			name="btn_close",type=1,typeName="Button",time=0,x=540,y=40,width=40,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_close.png"
		}
	}
}
return buyGoodsLayout;