local chatLayout=
{
	name="chatLayout",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,isLuaLocal=0,
	{
		name="img_bg",type=1,typeName="Image",time=0,x=0,y=0,width=884,height=584,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_common/img_noTitleBg.png",gridLeft=70,gridRight=70,gridTop=70,gridBottom=70,
		{
			name="view_chat",type=0,typeName="View",time=0,x=45,y=430,width=794,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="Image10",type=1,typeName="Image",time=0,x=-1,y=1,width=796,height=102,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_chat/img_divisionLine_bg.png"
			},
			{
				name="img_chatinput_bg",type=1,typeName="Image",time=0,x=12,y=20,width=600,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/input_bg.png",gridLeft=30,gridRight=30,gridTop=30,gridBottom=30,
				{
					name="View24",type=0,typeName="View",time=0,x=93,y=11,width=487,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
					{
						name="text_myInput",type=4,typeName="Text",time=0,x=-6,y=-2,width=500,height=59,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=0,colorGreen=0,colorBlue=0,string=[[点击输入(最多40个字符)]],isLock=0
					},
					{
						name="edittext_chatInfo",type=7,typeName="EditTextView",time=0,x=-6,y=-4,width=502,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=0,colorGreen=0,colorBlue=0,string=[[EditTextView]]
					}
				},
				{
					name="text_commonUser",type=4,typeName="Text",time=0,x=493,y=7,width=98,height=66,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[常用]]
				},
				{
					name="img_chatMark",type=1,typeName="Image",time=0,x=9,y=9,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_chat/img_chatMark.png",
					{
						name="Image22",type=1,typeName="Image",time=0,x=47,y=-13,width=32,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_chat/img_chatRed_bg.png",
						{
							name="text_hornNum",type=4,typeName="Text",time=0,x=0,y=-1,width=10,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[5]]
						}
					}
				},
				{
					name="btn_commonUser",type=1,typeName="Button",time=0,x=491,y=-15,width=104,height=95,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/button.png"
				}
			},
			{
				name="btn_sendChat",type=1,typeName="Button",time=0,x=618,y=17,width=171,height=81,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_blue_small.png",
				{
					name="text_send",type=4,typeName="Text",time=0,x=0,y=-4,width=60,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=35,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[发送]]
				}
			},
			{
				name="Text25",type=4,typeName="Text",time=0,x=381,y=540,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=102,colorBlue=0,string=[[Text]]
			}
		},
		{
			name="view_show",type=0,typeName="View",time=0,x=57,y=57,width=768,height=373,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="scrollview_chat",type=0,typeName="ScrollView",time=0,x=1,y=3,width=767,height=371,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
			}
		},
		{
			name="view_commonUserBar",type=0,typeName="View",time=0,x=436,y=353,width=387,height=94,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="Image26",type=1,typeName="Image",time=0,x=-251,y=-31,width=642,height=126,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_chat/img_commonUse_bg.png",
				{
					name="btn_seekTX",type=1,typeName="Button",time=0,x=16,y=20,width=190,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_red_small.png",
					{
						name="Text30",type=4,typeName="Text",time=0,x=0,y=0,width=90,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[找同乡]]
					}
				},
				{
					name="btn_seekGold",type=1,typeName="Button",time=0,x=228,y=20,width=190,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_red_small.png",
					{
						name="Text31",type=4,typeName="Text",time=0,x=0,y=0,width=90,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[求金币]]
					}
				},
				{
					name="btn_SQY",type=1,typeName="Button",time=0,x=440,y=20,width=190,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_red_small.png",
					{
						name="Text32",type=4,typeName="Text",time=0,x=0,y=0,width=51.45,height=24.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[三缺一]]
					}
				}
			}
		}
	}
}
return chatLayout;