local createRoomPopu=
{
	name="createRoomPopu",type=0,typeName="View",time=0,x=-5,y=7,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,isLuaLocal=0,
	{
		name="img_bg",type=1,typeName="Image",time=78651596,x=0,y=0,width=838,height=542,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_common/img_tanKuang_mid.png",gridLeft=100,gridRight=100,gridTop=100,gridBottom=100,
		{
			name="Image56",type=1,typeName="Image",time=0,x=0,y=-5,width=770,height=342,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_common/img_dikuang.png",gridLeft=15,gridRight=15,gridTop=15,gridBottom=15
		},
		{
			name="text_title",type=4,typeName="Text",time=0,x=0,y=28,width=200,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=50,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[创建包间]]
		}
	},
	{
		name="view_content",type=0,typeName="View",time=0,x=170,y=153,width=941,height=463,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="view_roundnum",type=0,typeName="View",time=0,x=38,y=52,width=892,height=101,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="Text60",type=4,typeName="Text",time=0,x=90,y=39,width=120,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[局数选择:]]
			},
			{
				name="text_jsinfo1",type=4,typeName="Text",time=0,x=308,y=39,width=56.65,height=28.35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[倍数]]
			},
			{
				name="text_jsinfo2",type=4,typeName="Text",time=0,x=436,y=39,width=56.65,height=28.35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[倍数]]
			},
			{
				name="text_jsinfo4",type=4,typeName="Text",time=0,x=693,y=39,width=56.65,height=28.35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[倍数]]
			},
			{
				name="text_jsinfo3",type=4,typeName="Text",time=0,x=567,y=39,width=56.65,height=28.35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[倍数]]
			},
			{
				name="btn_js1",type=1,typeName="Button",time=0,x=250,y=27,width=56,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_tanKuang/login/img_check.png"
			},
			{
				name="btn_js2",type=1,typeName="Button",time=0,x=380,y=27,width=56,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_tanKuang/login/img_check.png"
			},
			{
				name="btn_js3",type=1,typeName="Button",time=0,x=511,y=27,width=56,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_tanKuang/login/img_check.png"
			},
			{
				name="btn_js4",type=1,typeName="Button",time=0,x=639,y=27,width=56,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_tanKuang/login/img_check.png"
			}
		},
		{
			name="btn_create",type=1,typeName="Button",time=0,x=0,y=0,width=240,height=90,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="kwx_common/btn_blue_big.png",
			{
				name="Text92",type=4,typeName="Text",time=0,x=0,y=-5,width=80,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=40,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[创建]]
			}
		},
		{
			name="Text93",type=4,typeName="Text",time=0,x=0,y=98,width=221.65,height=23.35,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=20,textAlign=kAlignCenter,colorRed=255,colorGreen=204,colorBlue=51,string=[[创建房间需扣除1钻石]]
		},
		{
			name="view_multiply",type=0,typeName="View",time=0,x=38,y=154,width=892,height=104,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="Text60",type=4,typeName="Text",time=0,x=89,y=39,width=120,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[游戏玩法:]]
			},
			{
				name="text_bsinfo1",type=4,typeName="Text",time=0,x=311,y=39,width=56.65,height=28.35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[卡五星2倍]]
			},
			{
				name="text_bsinfo2",type=4,typeName="Text",time=0,x=551,y=39,width=56.65,height=28.35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[卡五星4倍]]
			},
			{
				name="btn_bs1",type=1,typeName="Button",time=0,x=249,y=27,width=56,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_tanKuang/login/img_check.png"
			},
			{
				name="btn_bs2",type=1,typeName="Button",time=0,x=493,y=27,width=56,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_tanKuang/login/img_check.png"
			}
		},
		{
			name="view_gamemode",type=0,typeName="View",time=0,x=37,y=259,width=797,height=65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="Text60",type=4,typeName="Text",time=0,x=94,y=33,width=120,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255
			},
			{
				name="text_type1",type=4,typeName="Text",time=0,x=314,y=33,width=66,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[漂]]
			},
			{
				name="text_type2",type=4,typeName="Text",time=0,x=488,y=39,width=56.65,height=28.35,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[卡五星4倍]]
			},
			{
				name="btn_type1",type=1,typeName="Button",time=0,x=252,y=21,width=56,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_tanKuang/login/img_check.png"
			},
			{
				name="btn_type2",type=1,typeName="Button",time=0,x=430,y=27,width=56,height=56,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_tanKuang/login/img_check.png"
			}
		}
	}
}
return createRoomPopu;