local eMailLayout=
{
	name="eMailLayout",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,isLuaLocal=0,isLock=0,
	{
		name="img_bg",type=1,typeName="Image",time=101876716,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/img_commonBG.jpg",isLock=0,
		{
			name="img_top",type=1,typeName="Image",time=101876717,x=0,y=0,width=1280,height=244,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/img_top.png",isLock=0,
			{
				name="btn_back",type=2,typeName="Button",time=101876718,x=27,y=9,width=82,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_back.png",isLock=0
			},
			{
				name="view_tag",type=0,typeName="View",time=101876719,x=88,y=13,width=795,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,isLock=0,
				{
					name="btn_friendmsg",type=2,typeName="Button",time=101876720,x=399,y=0,width=250,height=80,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagNormal.png",isLock=0,
					{
						name="Image23",type=1,typeName="Image",time=0,x=0,y=6,width=164,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_mail/str_friendmsgN.png"
					}
				},
				{
					name="btn_friendmsgClicked",type=2,typeName="Button",time=101876726,x=399,y=0,width=250,height=80,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagClicked.png",isLock=0,
					{
						name="Image24",type=1,typeName="Image",time=0,x=0,y=7,width=164,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_mail/str_friendmsgP.png"
					}
				},
				{
					name="btn_systemmsg",type=2,typeName="Button",time=101876730,x=149,y=0,width=250,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagNormal.png",isLock=0,
					{
						name="Image25",type=1,typeName="Image",time=0,x=0,y=6,width=164,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_mail/str_systemmsgN.png"
					}
				},
				{
					name="btn_systemmsgClicked",type=2,typeName="Button",time=101876732,x=148,y=-1,width=250,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagClicked.png",isLock=0,
					{
						name="Image22",type=1,typeName="Image",time=0,x=0,y=8,width=164,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_mail/str_systemmsgP.png"
					}
				}
			}
		},
		{
			name="img_mid",type=1,typeName="Image",time=101876734,x=0,y=0,width=1180,height=598,fillTopLeftX=50,fillTopLeftY=110,fillBottomRightX=50,fillBottomRightY=12,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/img_diKuang.png",gridLeft=50,gridRight=50,gridTop=50,gridBottom=50,isLock=1,
			{
				name="view_systemmsg",type=0,typeName="View",time=0,x=0,y=64,width=1180,height=525,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop
			},
			{
				name="view_friendmsg",type=0,typeName="View",time=0,x=0,y=10,width=1180,height=583,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,isLock=0
			},
			{
				name="img_msgtips",type=1,typeName="Image",time=0,x=0,y=11,width=1100,height=43,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_mail/inviteTipBg.png",gridLeft=20,gridRight=30,gridTop=20,gridBottom=20,
				{
					name="Text24",type=4,typeName="Text",time=0,x=0,y=0,width=300,height=28.55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignLeft,colorRed=204,colorGreen=204,colorBlue=204,string=[[只保留最近的100条记录]]
				}
			}
		},
		{
			name="text_nodata",type=4,typeName="Text",time=0,x=-21,y=37,width=100,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[暂无任何消息。]],isLock=0
		}
	}
}
return eMailLayout;