local friendItem=
{
	name="friendItem",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="view_item",type=0,typeName="View",time=0,x=10,y=10,width=740,height=98,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="View8",type=0,typeName="View",time=0,x=179,y=9,width=231,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="img_sex",type=1,typeName="Image",time=0,x=8,y=4,width=30,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/blank.png"
			},
			{
				name="text_nick",type=4,typeName="Text",time=0,x=54,y=6,width=134.15,height=24.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[好友昵称]]
			},
			{
				name="view_head",type=0,typeName="View",time=0,x=-94,y=-2,width=80,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
			}
		},
		{
			name="View81",type=0,typeName="View",time=0,x=180,y=54,width=235,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="img_coin",type=1,typeName="Image",time=0,x=8,y=4,width=30,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/img_coin.png"
			},
			{
				name="text_money",type=4,typeName="Text",time=0,x=53,y=6,width=134.15,height=24.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[999999]]
			}
		},
		{
			name="btn_add",type=1,typeName="Button",time=0,x=479,y=13,width=115,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/button.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="text_chat",type=4,typeName="Text",time=0,x=33,y=21,width=48.55,height=24.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=51,colorGreen=51,colorBlue=51,string=[[聊天]]
			}
		},
		{
			name="btn_add1",type=1,typeName="Button",time=0,x=616,y=13,width=115,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/button.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Text15",type=4,typeName="Text",time=0,x=33,y=21,width=48.55,height=24.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignLeft,colorRed=51,colorGreen=51,colorBlue=51,string=[[对战]]
			}
		},
		{
			name="img_rank",type=1,typeName="Image",time=0,x=-2,y=16,width=78,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/blank.png"
		}
	}
}
return friendItem;