local historyLayout=
{
	name="historyLayout",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="img_bg",type=1,typeName="Image",time=0,x=0,y=0,width=618,height=272,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/img_history.png",
		{
			name="Image3",type=1,typeName="Image",time=0,x=0,y=255,width=186,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_room/btn_history.png"
		}
	},
	{
		name="view_history",type=0,typeName="View",time=0,x=0,y=0,width=599,height=254,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="Text5",type=4,typeName="Text",time=0,x=-238,y=8,width=72,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[牌局数]]
		},
		{
			name="text_me",type=4,typeName="Text",time=0,x=-117,y=8,width=26,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[我]]
		},
		{
			name="text_play2",type=4,typeName="Text",time=0,x=27,y=8,width=26,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[玩家A]]
		},
		{
			name="text_play4",type=4,typeName="Text",time=0,x=195,y=8,width=26,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[玩家B]]
		},
		{
			name="scroll_history",type=0,typeName="ScrollView",time=0,x=-3,y=-1,width=592,height=163,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter
		},
		{
			name="Text52",type=4,typeName="Text",time=0,x=-248,y=218,width=26,height=27,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[总]]
		},
		{
			name="text_scoreme",type=4,typeName="Text",time=0,x=-111,y=217,width=93,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=95,string=[[0]]
		},
		{
			name="text_score2",type=4,typeName="Text",time=0,x=34,y=217,width=108,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=26,textAlign=kAlignCenter,colorRed=50,colorGreen=250,colorBlue=30,string=[[0]]
		},
		{
			name="text_score4",type=4,typeName="Text",time=0,x=195,y=219,width=74,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[0]]
		}
	}
}
return historyLayout;