local joinRoomPopu=
{
	name="joinRoomPopu",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,isLuaLocal=0,
	{
		name="img_bg",type=1,typeName="Image",time=78651596,x=0,y=0,width=838,height=542,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_common/img_tanKuang_mid.png",gridLeft=100,gridRight=100,gridTop=100,gridBottom=100,
		{
			name="Text58",type=4,typeName="Text",time=0,x=4,y=-216,width=160,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=40,textAlign=kAlignTop,colorRed=255,colorGreen=255,colorBlue=255,string=[[加入房间]]
		},
		{
			name="Image40",type=1,typeName="Image",time=0,x=0,y=25,width=777,height=394,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_common/img_dikuang.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20
		}
	},
	{
		name="view_entryfid",type=0,typeName="View",time=0,x=0,y=36,width=682,height=339,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
		{
			name="img_num1",type=1,typeName="Image",time=0,x=67,y=-1,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/img_entryK.png"
		},
		{
			name="img_num2",type=1,typeName="Image",time=0,x=161,y=-1,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/img_entryK.png"
		},
		{
			name="img_num3",type=1,typeName="Image",time=0,x=255,y=-1,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/img_entryK.png"
		},
		{
			name="img_num4",type=1,typeName="Image",time=0,x=349,y=-1,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/img_entryK.png"
		},
		{
			name="img_num5",type=1,typeName="Image",time=0,x=443,y=-1,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/img_entryK.png"
		},
		{
			name="img_num6",type=1,typeName="Image",time=0,x=537,y=-1,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/img_entryK.png"
		},
		{
			name="btn_num1",type=1,typeName="Button",time=0,x=19,y=85,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image41",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/1.png"
			}
		},
		{
			name="btn_num2",type=1,typeName="Button",time=0,x=185,y=85,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image42",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/2.png"
			}
		},
		{
			name="btn_num3",type=1,typeName="Button",time=0,x=351,y=85,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image43",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/3.png"
			}
		},
		{
			name="btn_num4",type=1,typeName="Button",time=0,x=517,y=85,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image44",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/4.png"
			}
		},
		{
			name="btn_num5",type=1,typeName="Button",time=0,x=19,y=168,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image45",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/5.png"
			}
		},
		{
			name="btn_num6",type=1,typeName="Button",time=0,x=185,y=168,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image47",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/6.png"
			}
		},
		{
			name="btn_num7",type=1,typeName="Button",time=0,x=351,y=168,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image48",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/7.png"
			}
		},
		{
			name="btn_num8",type=1,typeName="Button",time=0,x=517,y=168,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image49",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/8.png"
			}
		},
		{
			name="btn_num9",type=1,typeName="Button",time=0,x=19,y=251,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image50",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/9.png"
			}
		},
		{
			name="btn_num0",type=1,typeName="Button",time=0,x=185,y=251,width=140,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_yellow.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Image51",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/number2/0.png"
			}
		},
		{
			name="btn_del",type=1,typeName="Button",time=0,x=383,y=248,width=240,height=90,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/btn_red_big.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
			{
				name="Text85",type=4,typeName="Text",time=0,x=0,y=-4,width=12.85,height=24.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=40,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[删除]]
			}
		}
	}
}
return joinRoomPopu;