local LobbyLayout1=
{
	name="LobbyLayout1",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,isLuaLocal=0,
	{
		name="view_bg",type=0,typeName="View",time=76472797,x=0,y=0,width=200,height=150,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
		{
			name="scene_bg",type=1,typeName="Image",time=84089528,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTop,file="kwx_lobby/lobbyBackGround.jpg"
		},
		{
			name="buttom_bg",type=1,typeName="Image",time=89970069,x=0,y=0,width=1280,height=136,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="kwx_lobby/bottom.png"
		}
	},
	{
		name="view_ui",type=0,typeName="View",time=76473863,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
		{
			name="view_top",type=0,typeName="View",time=76474948,x=0,y=0,width=1280,height=130,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="view_nickName",type=0,typeName="View",time=89972699,x=105,y=10,width=200,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="img_login",type=1,typeName="Image",time=89972842,x=0,y=-5,width=38,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/img_guest.png"
				},
				{
					name="text_nick",type=4,typeName="Text",time=76493656,x=40,y=0,width=196,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=28,textAlign=kAlignTopLeft,colorRed=255,colorGreen=255,colorBlue=255
				}
			},
			{
				name="img_coinBg",type=1,typeName="Image",time=76495033,x=105,y=49,width=160,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/img_infoFrame.png",gridLeft=20,gridRight=20,
				{
					name="img_icon",type=1,typeName="Image",time=76495228,x=1,y=1,width=38,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/img_coin.png"
				},
				{
					name="view_coin",type=0,typeName="View",time=76495332,x=40,y=4,width=120,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
				}
			},
			{
				name="img_huaFeiBg",type=1,typeName="Image",time=89973782,x=265,y=49,width=148,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/img_infoFrame.png",gridLeft=20,gridRight=20,
				{
					name="img_huaFei",type=1,typeName="Image",time=89973783,x=3,y=1,width=46,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/img_huaFei.png"
				},
				{
					name="view_huaFei",type=0,typeName="View",time=89973784,x=48,y=4,width=90,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
				}
			},
			{
				name="btn_head",type=2,typeName="Button",time=76562826,x=0,y=-10,width=112,height=112,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/blank.png",
				{
					name="view_head",type=0,typeName="View",time=76563690,x=0,y=0,width=112,height=112,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
				},
				{
					name="img_headBg",type=1,typeName="Image",time=76563626,x=0,y=0,width=104,height=104,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="kwx_lobby/img_touXiangFrame.png"
				}
			},
			{
				name="view_logoBg",type=1,typeName="Image",time=89974297,x=0,y=0,width=330,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_lobby/logoBG.png",
				{
					name="view_logo",type=1,typeName="Image",time=89974722,x=0,y=0,width=214,height=84,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/logo.png"
				}
			},
			{
				name="btn_firstCharge",type=2,typeName="Button",time=89975052,x=390,y=0,width=110,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/btn_firstCharger.png"
			},
			{
				name="btn_sign",type=2,typeName="Button",time=89975096,x=390,y=0,width=110,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/btn_sign.png"
			},
			{
				name="btn_msg",type=2,typeName="Button",time=89975125,x=265,y=0,width=110,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/btn_msg.png",
				{
					name="img_mailmsgnum",type=1,typeName="Image",time=0,x=63,y=12,width=36,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/img_red.png",
					{
						name="text_mailnum",type=4,typeName="Text",time=0,x=-3,y=2,width=42,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[1]]
					}
				}
			},
			{
				name="btn_setting",type=2,typeName="Button",time=89975131,x=15,y=0,width=110,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/btn_setting.png",isLock=0,
				{
					name="bubble_setting_img",type=1,typeName="Image",time=90127072,x=10,y=10,width=36,height=38,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/img_red.png",isLock=0
				}
			},
			{
				name="btn_help",type=2,typeName="Button",time=94809513,x=140,y=0,width=110,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/btn_help.png"
			}
		},
		{
			name="view_bottom",type=0,typeName="View",time=76475084,x=0,y=5,width=1280,height=100,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
			{
				name="btn_shop",type=2,typeName="Button",time=76477159,x=80,y=0,width=140,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/btn_mall.png"
			},
			{
				name="btn_task",type=2,typeName="Button",time=76477209,x=275,y=0,width=140,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/btn_task.png",
				{
					name="bubble_task_img",type=1,typeName="Image",time=84533802,x=3,y=1,width=56,height=40,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/img_redNumbe.png",
					{
						name="bubble_task_txt",type=4,typeName="Text",time=84533803,x=0,y=0,width=56,height=40,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[1]]
					}
				},
				{
					name="bubble_task_img_l",type=1,typeName="Image",time=90126618,x=3,y=1,width=36,height=38,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/img_red.png",
					{
						name="bubble_task_txt_l",type=4,typeName="Text",time=90126619,x=0,y=0,width=56,height=40,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[1]]
					}
				}
			},
			{
				name="btn_quickStart",type=2,typeName="Button",time=76497515,x=0,y=0,width=342,height=140,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="kwx_lobby/btn_quickStart.png"
			},
			{
				name="btn_rank",type=2,typeName="Button",time=76477224,x=865,y=0,width=140,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/btn_rank.png",
				{
					name="bubble_rank_img",type=1,typeName="Image",time=84533797,x=3,y=1,width=56,height=40,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/img_redNumbe.png",
					{
						name="bubble_rank_txt",type=4,typeName="Text",time=84533798,x=0,y=-2,width=56,height=40,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[1]]
					}
				},
				{
					name="bubble_rank_img_l",type=1,typeName="Image",time=90126872,x=3,y=1,width=36,height=38,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/img_red.png",
					{
						name="bubble_task_txt_l",type=4,typeName="Text",time=90126873,x=0,y=0,width=56,height=40,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[1]]
					}
				}
			},
			{
				name="btn_activity",type=2,typeName="Button",time=76477231,x=1060,y=0,width=140,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/btn_activity.png",
				{
					name="bubble_act_img",type=1,typeName="Image",time=84505056,x=1,y=1,width=56,height=40,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/img_redNumbe.png",
					{
						name="bubble_act_txt",type=4,typeName="Text",time=84504993,x=0,y=-2,width=56,height=40,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[1]]
					}
				},
				{
					name="bubble_act_img_l",type=1,typeName="Image",time=90126911,x=3,y=1,width=36,height=38,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/img_red.png",
					{
						name="bubble_act_txt_l",type=4,typeName="Text",time=90126912,x=0,y=0,width=56,height=40,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[1]]
					}
				}
			}
		},
		{
			name="view_select",type=0,typeName="View",time=89436690,x=0,y=0,width=1280,height=420,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="btn_level1",type=2,typeName="Button",time=89437205,x=879,y=18,width=282,height=114,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/blank.png",
				{
					name="Image1",type=1,typeName="Image",time=90657897,x=0,y=0,width=282,height=318,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/btn_xuanChangFrame.png"
				},
				{
					name="Image2",type=1,typeName="Image",time=90657926,x=0,y=0,width=250,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/img_lianXiChang.png"
				},
				{
					name="animNode",type=0,typeName="View",time=95351556,x=0,y=0,width=200,height=150,visible=0,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter
				},
				{
					name="Image3",type=1,typeName="Image",time=92459137,x=0,y=-50,width=294,height=360,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_lobby/img_1.png"
				}
			},
			{
				name="btn_level2",type=2,typeName="Button",time=90658005,x=879,y=133,width=282,height=114,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/blank.png",
				{
					name="Image1",type=1,typeName="Image",time=90658006,x=0,y=0,width=282,height=318,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/btn_xuanChangFrame.png"
				},
				{
					name="Image2",type=1,typeName="Image",time=90658007,x=0,y=0,width=250,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/img_gaoJiChang.png"
				},
				{
					name="animNode",type=0,typeName="View",time=95351593,x=0,y=0,width=200,height=150,visible=0,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter
				},
				{
					name="Image4",type=1,typeName="Image",time=92459170,x=0,y=-50,width=294,height=360,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_lobby/img_2.png"
				}
			},
			{
				name="btn_level3",type=2,typeName="Button",time=90658035,x=879,y=246,width=282,height=114,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/blank.png",
				{
					name="Image1",type=1,typeName="Image",time=90658036,x=0,y=0,width=282,height=318,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_lobby/btn_xuanChangFrame.png"
				},
				{
					name="Image2",type=1,typeName="Image",time=90658037,x=0,y=0,width=250,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/img_yingHuafei.png"
				},
				{
					name="animNode",type=0,typeName="View",time=95351623,x=0,y=0,width=200,height=150,visible=0,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter
				},
				{
					name="Image5",type=1,typeName="Image",time=92459179,x=0,y=-50,width=294,height=360,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="kwx_lobby/img_3.png"
				}
			}
		},
		{
			name="btn_exchange",type=2,typeName="Button",time=90040704,x=0,y=410,width=62,height=152,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="kwx_lobby/btn_exchange.png"
		},
		{
			name="view_paomadeng",type=0,typeName="View",time=95830829,x=0,y=100,width=1024,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
			{
				name="img_paomadeng",type=1,typeName="Image",time=95830886,x=0,y=0,width=1024,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_lobby/img_paoMaDeng.png",
				{
					name="Image6",type=1,typeName="Image",time=95831190,x=10,y=0,width=40,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="kwx_lobby/img_laBa.png"
				}
			}
		}
	},
	{
		name="view_friend",type=0,typeName="View",time=0,x=-188,y=0,width=792,height=404,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
		{
			name="img_firendbg",type=1,typeName="Image",time=0,x=-19,y=23,width=752,height=347,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_erJiCommon/img_diKuang.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10
		},
		{
			name="view_tab",type=0,typeName="View",time=0,x=37,y=0,width=755,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,
			{
				name="btn_firend",type=1,typeName="Button",time=0,x=-2,y=-2,width=180,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagNormal.png",
				{
					name="Text73",type=4,typeName="Text",time=0,x=58,y=16,width=68.55,height=34.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=35,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[麻友]]
				}
			},
			{
				name="btn_addFriend",type=1,typeName="Button",time=0,x=188,y=-2,width=180,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagNormal.png",
				{
					name="Text74",type=4,typeName="Text",time=0,x=22,y=16,width=137.15,height=34.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=35,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[添加麻友]]
				}
			},
			{
				name="btn_friendGame",type=1,typeName="Button",time=0,x=383,y=-2,width=180,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagNormal.png",
				{
					name="Text75",type=4,typeName="Text",time=0,x=21,y=15,width=137.15,height=34.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=35,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[麻友开房]]
				}
			},
			{
				name="btn_searchbill",type=1,typeName="Button",time=0,x=574,y=-2,width=180,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagNormal.png",
				{
					name="Text76",type=4,typeName="Text",time=0,x=20,y=15,width=137.15,height=34.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=35,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[查询账单]]
				}
			},
			{
				name="btn_firendclick",type=1,typeName="Button",time=0,x=-2,y=-2,width=180,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagClicked.png",
				{
					name="Text73",type=4,typeName="Text",time=0,x=58,y=16,width=68.55,height=34.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=35,textAlign=kAlignLeft,colorRed=204,colorGreen=204,colorBlue=204,string=[[麻友]]
				}
			},
			{
				name="btn_addFriendclick",type=1,typeName="Button",time=0,x=188,y=-2,width=180,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagClicked.png",
				{
					name="Text74",type=4,typeName="Text",time=0,x=22,y=16,width=137.15,height=34.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=35,textAlign=kAlignLeft,string=[[添加麻友]],colorRed=204,colorGreen=204,colorBlue=204
				}
			},
			{
				name="btn_friendGameclick",type=1,typeName="Button",time=0,x=383,y=-2,width=180,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagClicked.png",
				{
					name="Text75",type=4,typeName="Text",time=0,x=21,y=15,width=137.15,height=34.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=35,textAlign=kAlignLeft,colorRed=204,colorGreen=204,colorBlue=204,string=[[麻友开房]]
				}
			},
			{
				name="btn_searchbillclick",type=1,typeName="Button",time=0,x=574,y=-2,width=180,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_tagClicked.png",
				{
					name="Text76",type=4,typeName="Text",time=0,x=20,y=15,width=137.15,height=34.3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=35,textAlign=kAlignLeft,colorRed=204,colorGreen=204,colorBlue=204,string=[[查询账单]]
				}
			}
		},
		{
			name="view_list",type=0,typeName="View",time=0,x=7,y=71,width=741,height=314,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="view_friendlist",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="scrollview_friendlist",type=0,typeName="ScrollView",time=0,x=0,y=0,width=740,height=315,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter
				},
				{
					name="view_addfirend1",type=0,typeName="View",time=0,x=152,y=90,width=463,height=80,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
					{
						name="btn_addfriend1",type=1,typeName="Button",time=0,x=0,y=0,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="kwx_friend/img_add.png"
					},
					{
						name="Text86",type=4,typeName="Text",time=0,x=73,y=26,width=390,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[暂无麻友，快来添加一个吧！]]
					}
				},
				{
					name="view_addfirend2",type=0,typeName="View",time=0,x=127,y=12,width=463,height=298,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
					{
						name="btn_addfriend2",type=1,typeName="Button",time=0,x=-7,y=-118,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="kwx_friend/img_add.png"
					},
					{
						name="Text86",type=4,typeName="Text",time=0,x=73,y=14,width=390,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[暂无麻友，快来添加一个吧！]]
					},
					{
						name="Text861",type=4,typeName="Text",time=0,x=-9,y=78,width=150,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[推荐好友：]]
					},
					{
						name="btn_change",type=1,typeName="Button",time=0,x=162,y=56,width=137,height=67,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/button.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
						{
							name="Text94",type=4,typeName="Text",time=0,x=25,y=20,width=74,height=23.75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[换一批]]
						}
					},
					{
						name="scrollview_tuijian",type=0,typeName="ScrollView",time=0,x=-9,y=135,width=478,height=167,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
					}
				}
			},
			{
				name="view_addfriend",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="view_friendfor",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
					{
						name="scrollview_friendfor",type=0,typeName="ScrollView",time=0,x=-2,y=-3,width=740,height=222,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop
					},
					{
						name="Image98",type=1,typeName="Image",time=0,x=46,y=229,width=519,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/img_enterKuang.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
						{
							name="edittext_gameid",type=6,typeName="EditText",time=0,x=22,y=3,width=456,height=45.75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignLeft,colorRed=0,colorGreen=0,colorBlue=0,string=[[搜索游戏ID]]
						},
						{
							name="text_gameid_tips",type=4,typeName="Text",time=0,x=22,y=-1,width=131,height=23.75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignLeft,colorRed=153,colorGreen=153,colorBlue=153,string=[[搜索游戏ID]]
						}
					},
					{
						name="btn_searchid",type=1,typeName="Button",time=0,x=591,y=220,width=116,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/button.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
						{
							name="Text100",type=4,typeName="Text",time=0,x=31,y=24,width=60,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[搜索]]
						}
					},
					{
						name="Text101",type=4,typeName="Text",time=0,x=52,y=296,width=252.5,height=23.75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=153,string=[[告诉好友我的id是：123]]
					}
				},
				{
					name="view_facetoface",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
					{
						name="View107",type=0,typeName="View",time=0,x=-3,y=-11,width=734,height=67,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
						{
							name="Image109",type=1,typeName="Image",time=0,x=0,y=1,width=746,height=65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/scenc_title_mid_bg2.png"
						},
						{
							name="btn_back_addfriend",type=1,typeName="Button",time=0,x=0,y=2,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_back.png"
						},
						{
							name="Text122",type=4,typeName="Text",time=0,x=296,y=17,width=144,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[面对面加好友]]
						}
					},
					{
						name="View110",type=0,typeName="View",time=0,x=0,y=27,width=737,height=245,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
						{
							name="Text113",type=4,typeName="Text",time=0,x=50,y=49,width=480,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=0,colorGreen=0,colorBlue=0,string=[[和朋友同时输入相同的四位数字即可互相成为麻友哦！]]
						},
						{
							name="Text1131",type=4,typeName="Text",time=0,x=48,y=85,width=480,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=20,textAlign=kAlignLeft,colorRed=153,colorGreen=153,colorBlue=153,string=[[（尽量不要使用类似0000 和1234 等过于简单的数字）]]
						},
						{
							name="Image118",type=1,typeName="Image",time=0,x=211,y=139,width=244,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_common/img_enterKuang.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
							{
								name="text_inputnum_tips",type=4,typeName="Text",time=0,x=32,y=20,width=180,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=153,colorGreen=153,colorBlue=153,string=[[输入四个数字]]
							},
							{
								name="edittext_inputnum",type=6,typeName="EditText",time=0,x=32,y=20,width=195,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignLeft,colorRed=0,colorGreen=0,colorBlue=0,string=[[输入四个数字]]
							}
						}
					}
				},
				{
					name="view_facetoface_1",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
					{
						name="View107",type=0,typeName="View",time=0,x=-3,y=-11,width=734,height=67,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
						{
							name="Image109",type=1,typeName="Image",time=0,x=0,y=1,width=746,height=65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/scenc_title_mid_bg2.png"
						},
						{
							name="btn_back_addfriend_1",type=1,typeName="Button",time=0,x=0,y=2,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_erJiCommon/btn_back.png"
						},
						{
							name="Text121",type=4,typeName="Text",time=0,x=305,y=20,width=147,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[面对面加好友]]
						}
					},
					{
						name="View110",type=0,typeName="View",time=0,x=0,y=27,width=737,height=245,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
						{
							name="Text113",type=4,typeName="Text",time=0,x=43,y=18,width=240,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=0,colorGreen=0,colorBlue=0,string=[[选择您想添加的好友：]]
						},
						{
							name="scrollview_facetoface",type=0,typeName="ScrollView",time=0,x=48,y=55,width=643,height=114,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
						},
						{
							name="btn_hjfriend",type=1,typeName="Button",time=0,x=250,y=179,width=212,height=75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/button.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
							{
								name="Text120",type=4,typeName="Text",time=0,x=61,y=30,width=96,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[互加好友]]
							}
						}
					}
				}
			},
			{
				name="view_friendgame",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="view_invitegame",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
					{
						name="btn_toset",type=1,typeName="Button",time=0,x=268,y=254,width=163,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/button.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
						{
							name="Text141",type=4,typeName="Text",time=0,x=47,y=27,width=72,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[下一步]]
						}
					},
					{
						name="ScrollView139",type=0,typeName="ScrollView",time=0,x=16,y=63,width=704,height=187,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
					},
					{
						name="View135",type=0,typeName="View",time=0,x=0,y=-14,width=744,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
						{
							name="Image136",type=1,typeName="Image",time=0,x=-5,y=3,width=746,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/scenc_title_mid_bg1.png"
						},
						{
							name="Text138",type=4,typeName="Text",time=0,x=238,y=23,width=270,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[选择麻友]]
						}
					}
				},
				{
					name="view_inviteset",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
					{
						name="btn_toset",type=1,typeName="Button",time=0,x=268,y=254,width=163,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/button.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
						{
							name="Text141",type=4,typeName="Text",time=0,x=0,y=5,width=48,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[创建]]
						}
					},
					{
						name="View135",type=0,typeName="View",time=0,x=0,y=-14,width=744,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
						{
							name="Image136",type=1,typeName="Image",time=0,x=-5,y=3,width=746,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/scenc_title_mid_bg1.png"
						},
						{
							name="Text138",type=4,typeName="Text",time=0,x=238,y=23,width=270,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[房间设置]]
						}
					},
					{
						name="view_dizhu",type=0,typeName="View",time=0,x=33,y=75,width=290,height=92,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
						{
							name="Text153",type=4,typeName="Text",time=0,x=21,y=-1,width=100,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[设置底注：]]
						},
						{
							name="view_inputNumber",type=0,typeName="View",time=0,x=6,y=31,width=275,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
							{
								name="btn_add",type=1,typeName="Button",time=0,x=218,y=8,width=40,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/btn_add.png"
							},
							{
								name="Image15",type=1,typeName="Image",time=0,x=64,y=8,width=144,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/img_number_bg.png",
								{
									name="editText_number",type=6,typeName="EditText",time=0,x=0,y=0,width=106,height=27,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=0,colorGreen=60,colorBlue=140,string=[[80]]
								}
							},
							{
								name="btn_cut",type=1,typeName="Button",time=0,x=13,y=8,width=40,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/btn_cut.png"
							}
						}
					},
					{
						name="view_piaoqian",type=0,typeName="View",time=0,x=389,y=75,width=290,height=92,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
						{
							name="Text153",type=4,typeName="Text",time=0,x=21,y=-1,width=100,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[设置漂钱：]]
						},
						{
							name="view_inputNumber",type=0,typeName="View",time=0,x=6,y=31,width=275,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
							{
								name="btn_add",type=1,typeName="Button",time=0,x=218,y=8,width=40,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/btn_add.png"
							},
							{
								name="Image15",type=1,typeName="Image",time=0,x=64,y=8,width=144,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/img_number_bg.png",
								{
									name="editText_number",type=6,typeName="EditText",time=0,x=0,y=0,width=106,height=27,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=0,colorGreen=60,colorBlue=140,string=[[80]]
								}
							},
							{
								name="btn_cut",type=1,typeName="Button",time=0,x=13,y=8,width=40,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="kwx_buyGoods/btn_cut.png"
							}
						}
					}
				}
			},
			{
				name="view_bill",type=0,typeName="View",time=0,x=0,y=0,width=740,height=315,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="scrollview_bill",type=0,typeName="ScrollView",time=0,x=0,y=0,width=740,height=315,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter
				}
			}
		}
	}
}
return LobbyLayout1;