local operatePanel=
{
	name="operatePanel",type=0,typeName="View",time=0,x=0,y=0,width=1266,height=176,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
	{
		name="operateView",type=0,typeName="View",time=79585383,x=118,y=6,width=200,height=150,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
		{
			name="opBg",type=1,typeName="Image",time=81655835,x=0,y=0,width=1110,height=114,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="kwx_room/gameOpeation/img_tipsBg.png",gridLeft=325,gridRight=325
		},
		{
			name="giveUpBtn",type=2,typeName="Button",time=65677546,x=0,y=0,width=108,height=108,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="kwx_room/gameOpeation/pass_btnnormal.png",file2="kwx_room/gameOpeation/pass_btnpress.png"
		},
		{
			name="huBtn",type=2,typeName="Button",time=78910432,x=0,y=0,width=128,height=128,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="kwx_room/gameOpeation/hu_btnnormal.png",file2="kwx_room/gameOpeation/hu_btnpress.png"
		},
		{
			name="tingBtn",type=2,typeName="Button",time=65677540,x=0,y=0,width=128,height=128,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="kwx_room/gameOpeation/ming-btnnormal.png",file2="kwx_room/gameOpeation/ming-btnpress.png"
		},
		{
			name="gangBtn",type=2,typeName="Button",time=65677527,x=0,y=0,width=128,height=128,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="kwx_room/gameOpeation/gang_btnnormal.png",file2="kwx_room/gameOpeation/gang_btnpress.png"
		},
		{
			name="pengBtn",type=2,typeName="Button",time=65677522,x=0,y=0,width=128,height=128,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="kwx_room/gameOpeation/peng_btnnormal.png",file2="kwx_room/gameOpeation/peng_btnpress.png"
		}
	},
	{
		name="passBtn",type=2,typeName="Button",time=79585591,x=0,y=0,width=108,height=108,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="kwx_room/gameOpeation/pass_btnnormal.png",file2="kwx_room/gameOpeation/pass_btnpress.png"
	},
	{
		name="img_liang",type=1,typeName="Image",time=95939917,x=0,y=0,width=1110,height=114,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_room/gameOpeation/img_tipsBg.png",
		{
			name="img_tips1",type=1,typeName="Image",time=95939246,x=185,y=0,width=474,height=60,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="kwx_room/gameOpeation/img_selectPai.png",
			{
				name="btn_liang",type=2,typeName="Button",time=95425890,x=500,y=0,width=240,height=90,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="kwx_common/btn_blue_big.png",
				{
					name="text_liang",type=4,typeName="Text",time=95426330,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[选择完成]]
				}
			}
		},
		{
			name="img_tips2",type=1,typeName="Image",time=95940347,x=0,y=0,width=274,height=60,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_room/gameOpeation/img_selectHu.png"
		},
		{
			name="img_tips3",type=1,typeName="Image",time=95940519,x=0,y=0,width=522,height=60,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="kwx_room/gameOpeation/img_selectNot.png"
		}
	}
}
return operatePanel;